# ETF轮动评分配置

# 因子权重（加总=1.0）
factor_weights:
  Momentum252: 0.50    # 12个月动量
  Momentum126: 0.35    # 6个月动量
  Momentum63: 0.15     # 3个月动量
  VOLATILITY_120D: -0.10  # 低波因子（负向）

# 组合构建参数
portfolio:
  n_holdings: 8        # 持仓数量
  max_single: 0.20     # 单票最大权重

# 流动性阈值
liquidity:
  min_amount_20d: 20000000  # 20日均成交额>2000万元
