# ETF下载管理器配置文件
# 统一的ETF数据下载配置

# 数据源配置
source: "tushare"
tushare_token: "4a24bcfff16f7593632e6c46976a83e6a26f8f565daa156cb9ea9c1f"  # Tushare API Token

# 数据目录配置
base_dir: "raw/ETF"
create_subdirs: true

# 时间范围配置 - 基于实际ETF上市时间优化
start_date: "20200102"  # 36只ETF从2020年开始
end_date: "20251014"     # 到今天（2025-10-14）
years_back: 6           # 下载最近6年数据，覆盖完整牛熊周期

# API请求配置
max_retries: 3
retry_delay: 1.0
request_delay: 0.2
timeout: 30

# 下载配置
batch_size: 50
parallel: false
download_types:
  - "daily"      # 日线数据
  # - "moneyflow"  # 资金流向数据（Tushare不提供ETF资金流向）
  # - "minutes"    # 分钟数据（较慢）
  # - "basic_info"  # 基础信息

# 输出配置
save_format: "parquet"  # parquet, csv
verbose: true

# ========================================
# ETF配置清单 - 完整43只ETF
# ========================================
# 说明：包含39只已下载 + 4只待补充的ETF，按优先级和类别分组管理

etf_list:
  # ======================================
  # 核心必配ETF - 市场主要指数 (3只)
  # ======================================
  core_etfs:
    name: "核心必配ETF"
    description: "市场主要指数，投资组合核心配置"
    etfs:
      - code: "510300.SH"
        name: "沪深300ETF"
        category: "市场规模"
        priority: 1
        description: "跟踪沪深300指数，A股市场核心基准"

      - code: "510050.SH"
        name: "上证50ETF"
        category: "市场规模"
        priority: 1
        description: "跟踪上证50指数，超大盘蓝筹代表"

      - code: "159949.SZ"
        name: "创业板50ETF"
        category: "市场规模"
        priority: 1
        description: "跟踪创业板50指数，创业板龙头代表"

  # ======================================
  # 市场规模ETF - 各级别市场指数 (3只)
  # ======================================
  market_cap_etfs:
    name: "市场规模ETF"
    description: "覆盖大、中、小盘各级别市场指数"
    etfs:
      - code: "159915.SZ"
        name: "创业板ETF"
        category: "市场规模"
        priority: 2
        description: "跟踪创业板综合指数"

      - code: "510500.SH"
        name: "中证500ETF"
        category: "市场规模"
        priority: 2
        description: "跟踪中证500指数，中盘股代表"

      - code: "512100.SH"
        name: "中证1000ETF"
        category: "市场规模"
        priority: 2
        description: "跟踪中证1000指数，小盘股代表"

  # ======================================
  # 行业主题ETF - 各主要投资主题 (22只)
  # ======================================
  sector_etfs:
    name: "行业主题ETF"
    description: "覆盖新能源、科技、消费、医药等主要行业"
    etfs:
      # 新能源系列 (4只)
      - code: "159819.SZ"
        name: "新能源车ETF"
        category: "新能源"
        priority: 2
        description: "跟踪中证新能源汽车指数"

      - code: "515030.SH"
        name: "新能源ETF基金"
        category: "新能源"
        priority: 3
        description: "跟踪中证新能源指数"

      - code: "515180.SH"
        name: "新能源车ETF基金"
        category: "新能源"
        priority: 3
        description: "跟踪新能源汽车产业指数"

      - code: "515790.SH"
        name: "光伏ETF"
        category: "新能源"
        priority: 3
        description: "跟踪中证光伏产业指数"

      # 科技系列 (7只)
      - code: "512480.SH"
        name: "半导体ETF"
        category: "科技"
        priority: 2
        description: "跟踪中华交易服务半导体芯片行业指数"

      - code: "516160.SH"
        name: "芯片ETF"
        category: "科技"
        priority: 3
        description: "跟踪国证半导体芯片指数"

      - code: "159995.SZ"
        name: "芯片龙头ETF"
        category: "科技"
        priority: 3
        description: "跟踪半导体龙头指数"

      - code: "159998.SZ"
        name: "消费电子ETF"
        category: "科技"
        priority: 3
        description: "跟踪中证消费电子主题指数"

      - code: "515650.SH"
        name: "智能制造ETF"
        category: "科技"
        priority: 3
        description: "跟踪中证智能制造主题指数"

      - code: "516520.SH"
        name: "通信ETF"
        category: "科技"
        priority: 3
        description: "跟踪中证全指通信设备指数"

      - code: "515210.SH"
        name: "钢铁ETF"
        category: "科技"
        priority: 3
        description: "跟踪中证钢铁指数"

      # 消费系列 (5只)
      - code: "159928.SZ"
        name: "消费ETF"
        category: "消费"
        priority: 2
        description: "跟踪中证主要消费指数"

      - code: "513500.SH"
        name: "食品饮料ETF"
        category: "消费"
        priority: 3
        description: "跟踪中证细分食品饮料产业主题指数"

      - code: "512690.SH"
        name: "酒ETF"
        category: "消费"
        priority: 3
        description: "跟踪中证酒指数"

      - code: "512720.SH"
        name: "消费50ETF"
        category: "消费"
        priority: 3
        description: "跟踪中证消费50指数"

      - code: "512980.SH"
        name: "家电ETF"
        category: "消费"
        priority: 3
        description: "跟踪中证家电指数，消费细分领域"

      # 医药健康 (3只)
      - code: "159883.SZ"
        name: "医疗ETF"
        category: "医药健康"
        priority: 2
        description: "跟踪中证医疗指数"

      - code: "512010.SH"
        name: "生物医药ETF"
        category: "医药健康"
        priority: 3
        description: "跟踪国证生物医药指数"

      - code: "159859.SZ"
        name: "生物医药ETF"
        category: "医药健康"
        priority: 3
        description: "跟踪国证生物医药指数，医药细分领域"

      # 金融地产 (3只)
      - code: "512800.SH"
        name: "银行ETF"
        category: "金融"
        priority: 2
        description: "跟踪中证银行指数"

      - code: "512880.SH"
        name: "证券ETF"
        category: "金融"
        priority: 2
        description: "跟踪中证全指证券公司指数"

      - code: "511380.SH"
        name: "红利ETF"
        category: "金融"
        priority: 2
        description: "跟踪上证红利指数"

      # 资源周期类 (3只)
      - code: "518880.SH"
        name: "环保ETF"
        category: "公用事业"
        priority: 3
        description: "跟踪中证环保产业50指数"

      - code: "159992.SZ"
        name: "能源ETF"
        category: "能源"
        priority: 3
        description: "跟踪中证能源指数"

      - code: "512400.SH"
        name: "有色金属ETF"
        category: "资源周期"
        priority: 2
        description: "跟踪中证有色金属指数，资源周期核心"

      # 贵金属类 (1只)
      - code: "518850.SH"
        name: "白银ETF"
        category: "贵金属"
        priority: 3
        description: "跟踪上海金交所白银现货价格，贵金属对冲工具"

  # ======================================
  # 创新成长ETF - 成长风格主题 (4只)
  # ======================================
  growth_etfs:
    name: "创新成长ETF"
    description: "聚焦创新、成长风格的投资主题"
    etfs:
      - code: "159801.SZ"
        name: "创成长ETF"
        category: "成长风格"
        priority: 2
        description: "跟踪创业板动量成长指数"

      - code: "516090.SH"
        name: "双创50ETF"
        category: "成长风格"
        priority: 3
        description: "跟踪中证科创创业50指数"

      - code: "588000.SH"
        name: "科创50ETF"
        category: "成长风格"
        priority: 2
        description: "跟踪上证科创板50成份指数"

      - code: "588200.SH"
        name: "科创板ETF"
        category: "成长风格"
        priority: 3
        description: "跟踪科创板指数"

  # ======================================
  # 固定收益ETF - 债券类产品 (2只)
  # ======================================
  bond_etfs:
    name: "固定收益ETF"
    description: "债券类ETF，提供稳健收益选择"
    etfs:
      - code: "511010.SH"
        name: "国债ETF"
        category: "债券"
        priority: 2
        description: "跟踪上证5年期国债指数"

      - code: "511260.SH"
        name: "十年国债ETF"
        category: "债券"
        priority: 3
        description: "跟踪上证10年期国债指数"

  # ======================================
  # 海外市场ETF - 跨境投资产品 (3只)
  # ======================================
  overseas_etfs:
    name: "海外市场ETF"
    description: "投资海外市场的ETF产品"
    etfs:
      - code: "159920.SZ"
        name: "恒生科技ETF"
        category: "海外市场"
        priority: 2
        description: "跟踪恒生科技指数，投资香港科技股"

      - code: "513100.SH"
        name: "纳指ETF"
        category: "海外市场"
        priority: 2
        description: "跟踪纳斯达克100指数"

      - code: "513130.SH"
        name: "恒生科技ETF港元"
        category: "海外市场"
        priority: 3
        description: "跟踪恒生科技指数，港元计价版本"

  # ======================================
  # 其他ETF - 金融等其他类别 (2只)
  # ======================================
  other_etfs:
    name: "其他ETF"
    description: "其他重要ETF类别"
    etfs:
      - code: "512660.SH"
        name: "军工ETF基金"
        category: "军工"
        priority: 2
        description: "跟踪中证军工指数"

      - code: "513050.SH"
        name: "军工ETF"
        category: "军工"
        priority: 2
        description: "跟踪中证军工指数"

# ========================================
# 配置使用说明
# ========================================
# 1. 总ETF数量: 43只 (39只已下载 + 4只待补充)
# 2. 优先级分布:
#    - 优先级1 (最高): 3只 (核心必配)
#    - 优先级2 (高): 17只 (重要配置，新增1只有色金属ETF)
#    - 优先级3 (一般): 23只 (可选配置)
# 3. 类别分布: 13个主要投资类别
# 4. 分组管理: 7个主要分组，便于维护
# 5. 待补充ETF (4只):
#    - 159859.SZ 生物医药ETF (医药细分)
#    - 512980.SH 家电ETF (消费细分)
#    - 512400.SH 有色金属ETF (资源周期核心)
#    - 518850.SH 白银ETF (贵金属对冲)
# ========================================