# ETF快速下载配置
# 适用于快速下载核心ETF

source: "tushare"
tushare_token: "${TUSHARE_TOKEN}"

base_dir: "raw/ETF"
create_subdirs: true

# 快速下载：只下载1年数据
start_date: null
end_date: null
years_back: 1

# 较快的API配置
max_retries: 2
retry_delay: 0.5
request_delay: 0.1
timeout: 15

batch_size: 20
parallel: false
download_types:
  - "daily"

exchanges:
  - "SH"
  - "SZ"
min_priority: "must_have"  # 只下载核心ETF

include_etfs: []
exclude_etfs: []

save_format: "parquet"
create_summary: true
verbose: true

validation:
  auto_validate: false
  check_integrity: true