# Pre-commit配置：防止未来函数
repos:
  - repo: local
    hooks:
      - id: future-function-check
        name: 检查未来函数使用
        entry: python scripts/check_future_functions.py
        language: system
        files: \.py$
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: grep-future-check
        name: Grep检查未来函数
        entry: bash -c 'grep -n "shift(-[0-9]\)\|future_\|lead_" "$@" || true'
        language: system
        files: \.py$
        pass_filenames: false
        always_run: true