execution_info:
  python_version: 3.11.9
  system_info:
    architecture: 64bit
    platform: Darwin
    processor: arm
  timestamp: '2025-10-03T00:56:22.005928'
screening_parameters:
  alpha_level: 0.05
  base_factors:
  - MA5
  - MA10
  - RSI14
  - MACD_12_26_9
  cache_root: ./cache
  commission_rate: 0.002
  correlation_threshold: 0.8
  data_root: ../因子输出
  description: 默认筛选配置
  enable_parallel: true
  factor_change_threshold: 0.05
  factor_data_root: ./data/factors
  fdr_method: benjamini_hochberg
  high_rank_threshold: 0.8
  ic_horizons:
  - 1
  - 3
  - 5
  - 10
  - 20
  log_level: INFO
  log_root: ./logs/screening
  market_impact_coeff: 0.1
  max_cost_threshold: 0.01
  max_missing_ratio: 0.8
  max_vif_threshold: 10.0
  max_workers: 4
  memory_limit_gb: 8.0
  min_data_points: 50
  min_ic_threshold: 0.015
  min_ir_threshold: 0.35
  min_momentum_samples: 120
  min_robustness_score: 0.6
  min_sample_size: 100
  min_stability_threshold: 0.6
  name: default
  output_dir: ./output
  output_root: ./data/screening_results
  price_data_root: ../raw/HK
  progress_report_interval: 50
  raw_data_root: ../raw
  rolling_window: 60
  save_detailed_metrics: true
  save_reports: true
  slippage_bps: 5.0
  symbols:
  - 0700.HK
  timeframes:
  - 60min
  timeout_minutes: 60
  vif_threshold: 5.0
  weights:
    independence: 0.2
    practicality: 0.1
    predictive_power: 0.35
    short_term_fitness: 0.1
    stability: 0.25
