"""
自动生成的因子模块 - 使用SHARED_CALCULATORS确保一致性
"""

from .overlap_generated import *
from .statistic_generated import *

# 导入手动创建的核心因子
from .technical import MACD, RSI, STOCH, MACDHistogram, MACDSignal

# 导入所有生成的因子
from .technical_generated import *
from .volume_generated import *

# 所有生成的因子类
GENERATED_FACTORS = [
    # 手动创建的核心因子
    RSI,
    MACD,
    MACDSignal,
    MACDHistogram,
    STOCH,
    # 自动生成的因子
    WILLR9,
    WILLR14,
    WILLR18,
    WILLR21,
    CCI10,
    CCI14,
    CCI20,
    RSI7,
    RSI10,
    RSI14,
    ATR7,
    ATR10,
    ATR14,
    TA_T3_5,
    TA_T3_10,
    TA_T3_20,
    TA_MIDPRICE_5,
    TA_MIDPRICE_10,
    TA_MIDPRICE_20,
    TA_SAR,
    TA_ADX_14,
    TA_ADXR_14,
    TA_AROON_14_up,
    TA_AROON_14_down,
    TA_AROONOSC_14,
    TA_CCI_14,
    TA_DX_14,
    TA_MFI_14,
    TA_MOM_10,
    TA_ROC_10,
    TA_ROCP_10,
    TA_ROCR_10,
    TA_ROCR100_10,
    TA_RSI_14,
    TA_TRIX_14,
    TA_ULTOSC_timeperiod17_timeperiod214_timeperiod328,
    TA_WILLR_14,
    TA_CDL2CROWS,
    TA_CDL3BLACKCROWS,
    TA_CDL3INSIDE,
    TA_CDL3OUTSIDE,
    TA_CDL3WHITESOLDIERS,
    TA_CDLABANDONEDBABY,
    TA_CDLADVANCEBLOCK,
    TA_CDLBELTHOLD,
    TA_CDLBREAKAWAY,
    TA_CDLCONCEALBABYSWALL,
    TA_CDLCOUNTERATTACK,
    TA_CDLDARKCLOUDCOVER,
    TA_CDLDOJI,
    TA_CDLDRAGONFLYDOJI,
    TA_CDLENGULFING,
    TA_CDLGAPSIDESIDEWHITE,
    TA_CDLHAMMER,
    TA_CDLHARAMI,
    TA_CDLHARAMICROSS,
    TA_CDLHIGHWAVE,
    TA_CDLHIKKAKE,
    TA_CDLHOMINGPIGEON,
    TA_CDLIDENTICAL3CROWS,
    TA_CDLINNECK,
    TA_CDLINVERTEDHAMMER,
    TA_CDLKICKING,
    TA_CDLKICKINGBYLENGTH,
    TA_CDLLADDERBOTTOM,
    TA_CDLLONGLEGGEDDOJI,
    TA_CDLLONGLINE,
    TA_CDLONNECK,
    TA_CDLPIERCING,
    TA_CDLRISEFALL3METHODS,
    TA_CDLSEPARATINGLINES,
    TA_CDLSHORTLINE,
    TA_CDLSPINNINGTOP,
    TA_CDLTAKURI,
    TA_CDLTASUKIGAP,
    TA_CDLUNIQUE3RIVER,
    TA_CDLUPSIDEGAP2CROWS,
    TA_CDLXSIDEGAP3METHODS,
    Momentum1,
    Momentum3,
    Momentum5,
    Momentum8,
    Momentum10,
    Momentum12,
    Momentum15,
    Momentum20,
    Position5,
    Position8,
    Position10,
    Position12,
    Position15,
    Position20,
    Position25,
    Position30,
    Trend5,
    Trend8,
    Trend10,
    Trend12,
    Trend15,
    Trend20,
    Trend25,
    STOCH_7_10,
    STOCH_10_14,
    STOCH_14_20,
    MSTD5,
    MSTD10,
    MSTD15,
    FIXLB3,
    FIXLB5,
    FIXLB8,
    FIXLB10,
    FMEAN5,
    FMIN5,
    FSTD5,
    FMEAN10,
    FMIN10,
    FSTD10,
    FMEAN15,
    FMIN15,
    FSTD15,
    FMEAN20,
    FMIN20,
    FSTD20,
    LEXLB3,
    LEXLB5,
    LEXLB8,
    LEXLB10,
    MEANLB3,
    MEANLB5,
    MEANLB8,
    MEANLB10,
    TRENDLB3,
    TRENDLB5,
    TRENDLB8,
    TRENDLB10,
    RAND,
    RANDX,
    RANDNX,
    RPROB,
    RPROBX,
    RPROBCX,
    RPROBNX,
    STX,
    STCX,
    TA_STOCH_K,
    TA_STOCH_D,
    TA_STOCHF_K,
    TA_STOCHF_D,
    TA_STOCHRSI_fastd_period3_fastk_period5_timeperiod14_K,
    TA_STOCHRSI_fastd_period3_fastk_period5_timeperiod14_D,
    TA_CDL3LINESTRIKE,
    TA_CDL3STARSINSOUTH,
    TA_CDLDOJISTAR,
    TA_CDLEVENINGDOJISTAR,
    TA_CDLEVENINGSTAR,
    TA_CDLGRAVESTONEDOJI,
    TA_CDLMORNINGDOJISTAR,
    TA_CDLMORNINGSTAR,
    TA_CDLSHOOTINGSTAR,
    TA_CDLSTALLEDPATTERN,
    TA_CDLSTICKSANDWICH,
    TA_CDLTHRUSTING,
    TA_CDLTRISTAR,
    Volume_Ratio10,
    Volume_Momentum10,
    Volume_Ratio15,
    Volume_Momentum15,
    Volume_Ratio20,
    Volume_Momentum20,
    Volume_Ratio25,
    Volume_Momentum25,
    Volume_Ratio30,
    Volume_Momentum30,
    VWAP10,
    VWAP15,
    VWAP20,
    VWAP25,
    VWAP30,
    OBV,
    MA3,
    MA5,
    MA8,
    MA10,
    MA15,
    MA20,
    EMA3,
    EMA5,
    EMA8,
    EMA12,
    EMA15,
    EMA20,
    MACD_6_13_4,
    MACD_8_17_5,
    MACD_12_26_9,
    BB_10_2_0_Upper,
    BB_10_2_0_Middle,
    BB_10_2_0_Lower,
    BB_10_2_0_Width,
    BB_15_2_0_Upper,
    BB_15_2_0_Middle,
    BB_15_2_0_Lower,
    BB_15_2_0_Width,
    BB_20_2_0_Upper,
    BB_20_2_0_Middle,
    BB_20_2_0_Lower,
    BB_20_2_0_Width,
    OBV_SMA5,
    OBV_SMA10,
    OBV_SMA15,
    OBV_SMA20,
    BOLB_20,
    FMAX5,
    FMAX10,
    FMAX15,
    FMAX20,
    TA_SMA_5,
    TA_SMA_10,
    TA_SMA_20,
    TA_SMA_30,
    TA_SMA_60,
    TA_EMA_5,
    TA_EMA_10,
    TA_EMA_20,
    TA_EMA_30,
    TA_EMA_60,
    TA_WMA_5,
    TA_WMA_10,
    TA_WMA_20,
    TA_DEMA_5,
    TA_DEMA_10,
    TA_DEMA_20,
    TA_TEMA_5,
    TA_TEMA_10,
    TA_TEMA_20,
    TA_TRIMA_5,
    TA_TRIMA_10,
    TA_TRIMA_20,
    TA_KAMA_10,
    TA_KAMA_20,
    TA_APO_fastperiod12_matype0_slowperiod26,
    TA_CDLCLOSINGMARUBOZU,
    TA_CDLHANGINGMAN,
    TA_CDLMARUBOZU,
    TA_CDLMATCHINGLOW,
    TA_CDLMATHOLD,
    TA_CDLRICKSHAWMAN,
]

# 因子ID到类的映射
FACTOR_CLASS_MAP = {
    # 手动创建的核心因子
    "RSI": RSI,
    "MACD": MACD,
    "MACDSignal": MACDSignal,
    "MACDHistogram": MACDHistogram,
    "STOCH": STOCH,
    # 自动生成的因子
    "WILLR9": WILLR9,
    "WILLR14": WILLR14,
    "WILLR18": WILLR18,
    "WILLR21": WILLR21,
    "CCI10": CCI10,
    "CCI14": CCI14,
    "CCI20": CCI20,
    "RSI7": RSI7,
    "RSI10": RSI10,
    "RSI14": RSI14,
    "ATR7": ATR7,
    "ATR10": ATR10,
    "ATR14": ATR14,
    "TA_T3_5": TA_T3_5,
    "TA_T3_10": TA_T3_10,
    "TA_T3_20": TA_T3_20,
    "TA_MIDPRICE_5": TA_MIDPRICE_5,
    "TA_MIDPRICE_10": TA_MIDPRICE_10,
    "TA_MIDPRICE_20": TA_MIDPRICE_20,
    "TA_SAR": TA_SAR,
    "TA_ADX_14": TA_ADX_14,
    "TA_ADXR_14": TA_ADXR_14,
    "TA_AROON_14_up": TA_AROON_14_up,
    "TA_AROON_14_down": TA_AROON_14_down,
    "TA_AROONOSC_14": TA_AROONOSC_14,
    "TA_CCI_14": TA_CCI_14,
    "TA_DX_14": TA_DX_14,
    "TA_MFI_14": TA_MFI_14,
    "TA_MOM_10": TA_MOM_10,
    "TA_ROC_10": TA_ROC_10,
    "TA_ROCP_10": TA_ROCP_10,
    "TA_ROCR_10": TA_ROCR_10,
    "TA_ROCR100_10": TA_ROCR100_10,
    "TA_RSI_14": TA_RSI_14,
    "TA_TRIX_14": TA_TRIX_14,
    "TA_ULTOSC_timeperiod17_timeperiod214_timeperiod328": TA_ULTOSC_timeperiod17_timeperiod214_timeperiod328,
    "TA_WILLR_14": TA_WILLR_14,
    "TA_CDL2CROWS": TA_CDL2CROWS,
    "TA_CDL3BLACKCROWS": TA_CDL3BLACKCROWS,
    "TA_CDL3INSIDE": TA_CDL3INSIDE,
    "TA_CDL3OUTSIDE": TA_CDL3OUTSIDE,
    "TA_CDL3WHITESOLDIERS": TA_CDL3WHITESOLDIERS,
    "TA_CDLABANDONEDBABY": TA_CDLABANDONEDBABY,
    "TA_CDLADVANCEBLOCK": TA_CDLADVANCEBLOCK,
    "TA_CDLBELTHOLD": TA_CDLBELTHOLD,
    "TA_CDLBREAKAWAY": TA_CDLBREAKAWAY,
    "TA_CDLCONCEALBABYSWALL": TA_CDLCONCEALBABYSWALL,
    "TA_CDLCOUNTERATTACK": TA_CDLCOUNTERATTACK,
    "TA_CDLDARKCLOUDCOVER": TA_CDLDARKCLOUDCOVER,
    "TA_CDLDOJI": TA_CDLDOJI,
    "TA_CDLDRAGONFLYDOJI": TA_CDLDRAGONFLYDOJI,
    "TA_CDLENGULFING": TA_CDLENGULFING,
    "TA_CDLGAPSIDESIDEWHITE": TA_CDLGAPSIDESIDEWHITE,
    "TA_CDLHAMMER": TA_CDLHAMMER,
    "TA_CDLHARAMI": TA_CDLHARAMI,
    "TA_CDLHARAMICROSS": TA_CDLHARAMICROSS,
    "TA_CDLHIGHWAVE": TA_CDLHIGHWAVE,
    "TA_CDLHIKKAKE": TA_CDLHIKKAKE,
    "TA_CDLHOMINGPIGEON": TA_CDLHOMINGPIGEON,
    "TA_CDLIDENTICAL3CROWS": TA_CDLIDENTICAL3CROWS,
    "TA_CDLINNECK": TA_CDLINNECK,
    "TA_CDLINVERTEDHAMMER": TA_CDLINVERTEDHAMMER,
    "TA_CDLKICKING": TA_CDLKICKING,
    "TA_CDLKICKINGBYLENGTH": TA_CDLKICKINGBYLENGTH,
    "TA_CDLLADDERBOTTOM": TA_CDLLADDERBOTTOM,
    "TA_CDLLONGLEGGEDDOJI": TA_CDLLONGLEGGEDDOJI,
    "TA_CDLLONGLINE": TA_CDLLONGLINE,
    "TA_CDLONNECK": TA_CDLONNECK,
    "TA_CDLPIERCING": TA_CDLPIERCING,
    "TA_CDLRISEFALL3METHODS": TA_CDLRISEFALL3METHODS,
    "TA_CDLSEPARATINGLINES": TA_CDLSEPARATINGLINES,
    "TA_CDLSHORTLINE": TA_CDLSHORTLINE,
    "TA_CDLSPINNINGTOP": TA_CDLSPINNINGTOP,
    "TA_CDLTAKURI": TA_CDLTAKURI,
    "TA_CDLTASUKIGAP": TA_CDLTASUKIGAP,
    "TA_CDLUNIQUE3RIVER": TA_CDLUNIQUE3RIVER,
    "TA_CDLUPSIDEGAP2CROWS": TA_CDLUPSIDEGAP2CROWS,
    "TA_CDLXSIDEGAP3METHODS": TA_CDLXSIDEGAP3METHODS,
    "Momentum1": Momentum1,
    "Momentum3": Momentum3,
    "Momentum5": Momentum5,
    "Momentum8": Momentum8,
    "Momentum10": Momentum10,
    "Momentum12": Momentum12,
    "Momentum15": Momentum15,
    "Momentum20": Momentum20,
    "Position5": Position5,
    "Position8": Position8,
    "Position10": Position10,
    "Position12": Position12,
    "Position15": Position15,
    "Position20": Position20,
    "Position25": Position25,
    "Position30": Position30,
    "Trend5": Trend5,
    "Trend8": Trend8,
    "Trend10": Trend10,
    "Trend12": Trend12,
    "Trend15": Trend15,
    "Trend20": Trend20,
    "Trend25": Trend25,
    "STOCH_7_10": STOCH_7_10,
    "STOCH_10_14": STOCH_10_14,
    "STOCH_14_20": STOCH_14_20,
    "MSTD5": MSTD5,
    "MSTD10": MSTD10,
    "MSTD15": MSTD15,
    "FIXLB3": FIXLB3,
    "FIXLB5": FIXLB5,
    "FIXLB8": FIXLB8,
    "FIXLB10": FIXLB10,
    "FMEAN5": FMEAN5,
    "FMIN5": FMIN5,
    "FSTD5": FSTD5,
    "FMEAN10": FMEAN10,
    "FMIN10": FMIN10,
    "FSTD10": FSTD10,
    "FMEAN15": FMEAN15,
    "FMIN15": FMIN15,
    "FSTD15": FSTD15,
    "FMEAN20": FMEAN20,
    "FMIN20": FMIN20,
    "FSTD20": FSTD20,
    "LEXLB3": LEXLB3,
    "LEXLB5": LEXLB5,
    "LEXLB8": LEXLB8,
    "LEXLB10": LEXLB10,
    "MEANLB3": MEANLB3,
    "MEANLB5": MEANLB5,
    "MEANLB8": MEANLB8,
    "MEANLB10": MEANLB10,
    "TRENDLB3": TRENDLB3,
    "TRENDLB5": TRENDLB5,
    "TRENDLB8": TRENDLB8,
    "TRENDLB10": TRENDLB10,
    "RAND": RAND,
    "RANDX": RANDX,
    "RANDNX": RANDNX,
    "RPROB": RPROB,
    "RPROBX": RPROBX,
    "RPROBCX": RPROBCX,
    "RPROBNX": RPROBNX,
    "STX": STX,
    "STCX": STCX,
    "TA_STOCH_K": TA_STOCH_K,
    "TA_STOCH_D": TA_STOCH_D,
    "TA_STOCHF_K": TA_STOCHF_K,
    "TA_STOCHF_D": TA_STOCHF_D,
    "TA_STOCHRSI_fastd_period3_fastk_period5_timeperiod14_K": TA_STOCHRSI_fastd_period3_fastk_period5_timeperiod14_K,
    "TA_STOCHRSI_fastd_period3_fastk_period5_timeperiod14_D": TA_STOCHRSI_fastd_period3_fastk_period5_timeperiod14_D,
    "TA_CDL3LINESTRIKE": TA_CDL3LINESTRIKE,
    "TA_CDL3STARSINSOUTH": TA_CDL3STARSINSOUTH,
    "TA_CDLDOJISTAR": TA_CDLDOJISTAR,
    "TA_CDLEVENINGDOJISTAR": TA_CDLEVENINGDOJISTAR,
    "TA_CDLEVENINGSTAR": TA_CDLEVENINGSTAR,
    "TA_CDLGRAVESTONEDOJI": TA_CDLGRAVESTONEDOJI,
    "TA_CDLMORNINGDOJISTAR": TA_CDLMORNINGDOJISTAR,
    "TA_CDLMORNINGSTAR": TA_CDLMORNINGSTAR,
    "TA_CDLSHOOTINGSTAR": TA_CDLSHOOTINGSTAR,
    "TA_CDLSTALLEDPATTERN": TA_CDLSTALLEDPATTERN,
    "TA_CDLSTICKSANDWICH": TA_CDLSTICKSANDWICH,
    "TA_CDLTHRUSTING": TA_CDLTHRUSTING,
    "TA_CDLTRISTAR": TA_CDLTRISTAR,
    "Volume_Ratio10": Volume_Ratio10,
    "Volume_Momentum10": Volume_Momentum10,
    "Volume_Ratio15": Volume_Ratio15,
    "Volume_Momentum15": Volume_Momentum15,
    "Volume_Ratio20": Volume_Ratio20,
    "Volume_Momentum20": Volume_Momentum20,
    "Volume_Ratio25": Volume_Ratio25,
    "Volume_Momentum25": Volume_Momentum25,
    "Volume_Ratio30": Volume_Ratio30,
    "Volume_Momentum30": Volume_Momentum30,
    "VWAP10": VWAP10,
    "VWAP15": VWAP15,
    "VWAP20": VWAP20,
    "VWAP25": VWAP25,
    "VWAP30": VWAP30,
    "OBV": OBV,
    "MA3": MA3,
    "MA5": MA5,
    "MA8": MA8,
    "MA10": MA10,
    "MA15": MA15,
    "MA20": MA20,
    "EMA3": EMA3,
    "EMA5": EMA5,
    "EMA8": EMA8,
    "EMA12": EMA12,
    "EMA15": EMA15,
    "EMA20": EMA20,
    "MACD_6_13_4": MACD_6_13_4,
    "MACD_8_17_5": MACD_8_17_5,
    "MACD_12_26_9": MACD_12_26_9,
    "BB_10_2.0_Upper": BB_10_2_0_Upper,
    "BB_10_2.0_Middle": BB_10_2_0_Middle,
    "BB_10_2.0_Lower": BB_10_2_0_Lower,
    "BB_10_2.0_Width": BB_10_2_0_Width,
    "BB_15_2.0_Upper": BB_15_2_0_Upper,
    "BB_15_2.0_Middle": BB_15_2_0_Middle,
    "BB_15_2.0_Lower": BB_15_2_0_Lower,
    "BB_15_2.0_Width": BB_15_2_0_Width,
    "BB_20_2.0_Upper": BB_20_2_0_Upper,
    "BB_20_2.0_Middle": BB_20_2_0_Middle,
    "BB_20_2.0_Lower": BB_20_2_0_Lower,
    "BB_20_2.0_Width": BB_20_2_0_Width,
    "OBV_SMA5": OBV_SMA5,
    "OBV_SMA10": OBV_SMA10,
    "OBV_SMA15": OBV_SMA15,
    "OBV_SMA20": OBV_SMA20,
    "BOLB_20": BOLB_20,
    "FMAX5": FMAX5,
    "FMAX10": FMAX10,
    "FMAX15": FMAX15,
    "FMAX20": FMAX20,
    "TA_SMA_5": TA_SMA_5,
    "TA_SMA_10": TA_SMA_10,
    "TA_SMA_20": TA_SMA_20,
    "TA_SMA_30": TA_SMA_30,
    "TA_SMA_60": TA_SMA_60,
    "TA_EMA_5": TA_EMA_5,
    "TA_EMA_10": TA_EMA_10,
    "TA_EMA_20": TA_EMA_20,
    "TA_EMA_30": TA_EMA_30,
    "TA_EMA_60": TA_EMA_60,
    "TA_WMA_5": TA_WMA_5,
    "TA_WMA_10": TA_WMA_10,
    "TA_WMA_20": TA_WMA_20,
    "TA_DEMA_5": TA_DEMA_5,
    "TA_DEMA_10": TA_DEMA_10,
    "TA_DEMA_20": TA_DEMA_20,
    "TA_TEMA_5": TA_TEMA_5,
    "TA_TEMA_10": TA_TEMA_10,
    "TA_TEMA_20": TA_TEMA_20,
    "TA_TRIMA_5": TA_TRIMA_5,
    "TA_TRIMA_10": TA_TRIMA_10,
    "TA_TRIMA_20": TA_TRIMA_20,
    "TA_KAMA_10": TA_KAMA_10,
    "TA_KAMA_20": TA_KAMA_20,
    "TA_APO_fastperiod12_matype0_slowperiod26": TA_APO_fastperiod12_matype0_slowperiod26,
    "TA_CDLCLOSINGMARUBOZU": TA_CDLCLOSINGMARUBOZU,
    "TA_CDLHANGINGMAN": TA_CDLHANGINGMAN,
    "TA_CDLMARUBOZU": TA_CDLMARUBOZU,
    "TA_CDLMATCHINGLOW": TA_CDLMATCHINGLOW,
    "TA_CDLMATHOLD": TA_CDLMATHOLD,
    "TA_CDLRICKSHAWMAN": TA_CDLRICKSHAWMAN,
}
