application:
  allow_empty_result: false
  apply_in_is_stage: true
  empty_result_strategy: fallback_to_top_ic
correlation_deduplication:
  description: '当两个因子的相关系数 > 0.8 时:


    【默认策略 keep_higher_ic】

    1. 计算两个因子各自的当期IS IC

    2. 保留IC更高的因子

    3. 排除另一个因子


    【Factor Momentum 策略 keep_higher_icir】

    1. 计算两个因子各自的历史ICIR（信息比率 = mean(OOS IC) / std(OOS IC)）

    2. 使用最近K个窗口的OOS IC（K=icir_min_windows）

    3. 保留ICIR更高的因子（历史稳定性更强）

    4. 历史窗口不足K个的因子ICIR=0（自然劣势）


    目的: 避免因子空间中的冗余方向，保持因子组合的独立性

    '
  icir_min_windows: 3
  icir_std_floor: 0.005
  strategy: keep_higher_ic
  threshold: 0.9
description: "当前无必选因子配置。可根据策略需要添加。\n\n示例 (若需要):\n  required_factors:\n    - 'MOM_20D'\
  \        # 必选: 动量因子\n    - 'RET_VOL_20D'    # 必选: 波动率因子\n\n# A方案辅助过滤因子说明 (不参与因子选择，仅用于成本/容量约束):\n\
  #   - REALIZED_VOL_20D: 实际波动率（风险过滤、目标波动策略）\n#   - AMIHUD_ILLIQUIDITY: 流动性指标（冲击成本代理，100万资金关键约束）\n\
  #   - SPREAD_PROXY: 价差代理（交易成本估计）\n#   这些因子在后处理阶段（持仓构建）使用，不影响因子选择过程。\n"
factor_selection: null
family_quota:
  breakout_family:
    enabled: false
  correlation:
    description: 相关性类因子最多选 1 个
    factors:
    - PV_CORR_20D
    max_count: 1
  flow_accel_family:
    enabled: false
  momentum:
    description: 动量类因子最多选 1 个 (避免同向冗余)
    factors:
    - MOM_20D
    - SLOPE_20D
    max_count: 1
  price_features:
    description: 价格特征类最多选 1 个 (长短周期择一)
    factors:
    - PRICE_POSITION_20D
    - PRICE_POSITION_120D
    max_count: 1
  risk_adjusted:
    description: 风险调整类因子最多选 1 个
    factors:
    - MAX_DD_60D
    max_count: 1
  technical:
    description: 技术指标类最多选 1 个
    factors:
    - RSI_14
    max_count: 1
  tsmom_family:
    enabled: false
  volatility:
    description: 波动率类因子最多选 2 个 (覆盖不同周期)
    factors:
    - RET_VOL_20D
    - VOL_RATIO_20D
    - VOL_RATIO_60D
    max_count: 2
meta_factor_weighting:
  beta: 0.8
  enabled: true
  min_windows: 5
  mode: icir
metadata:
  created_date: '2025-10-26'
  description: ETF 轮动因子筛选系统 Step 5 约束配置 + A方案增量因子（灰度测试）
  last_modified: '2025-10-28'
  new_factors_status: disabled_by_default
  total_constraints: 5
  total_factors: 13
  total_families: 9
  version: '1.1'
minimum_ic:
  description: '全局最小IC要求: 0.012 (优化后: IC中位数水平)


    因子筛选逻辑:

    1. 首先按 IC > global_minimum 过滤候选因子

    2. 再应用家族配额、互斥对等约束

    3. 最后从满足条件的候选中按IC排序选择


    优化说明:

    - 从0.02降至0.012 (IS IC中位数)

    - 统计数据显示50%因子IC > 0.012

    - 预期平均2.5+因子/窗口 (vs 原1.56)

    - 避免过度严格导致候选池不足


    注: 该阈值可在 WFO 配置中覆盖 (是下界)

    '
  global_minimum: 0.012
mutual_exclusivity:
- pair:
  - PRICE_POSITION_20D
  - PRICE_POSITION_120D
  reason: 不同周期的价格位置指标功能重叠，选择周期最相关的一个
  severity: hard
- pair:
  - MOM_20D
  - SLOPE_20D
  reason: 动量和斜率反映相同的趋势特征，选择IC最高的一个
  severity: hard
- pair:
  - VOL_RATIO_20D
  - VOL_RATIO_60D
  reason: 不同周期的波动率比，若两者IC都高则选择回测表现更好的
  severity: soft
required_factors: []
validation:
  generate_report: true
  report_include:
  - candidate_factors
  - applied_constraints
  - constraint_impacts
  - final_selection
  - selection_reasons
  validate_config: true
