application:
  allow_empty_result: false
  apply_in_is_stage: true
  empty_result_strategy: fallback_to_top_ic
correlation_deduplication:
  description: '当两个因子的相关系数 > 0.8 时:


    【默认策略 keep_higher_ic】

    1. 计算两个因子各自的当期IS IC

    2. 保留IC更高的因子

    3. 排除另一个因子


    【Factor Momentum 策略 keep_higher_icir】

    1. 计算两个因子各自的历史ICIR（信息比率 = mean(OOS IC) / std(OOS IC)）

    2. 使用最近K个窗口的OOS IC（K=icir_min_windows）

    3. 保留ICIR更高的因子（历史稳定性更强）

    4. 历史窗口不足K个的因子ICIR=0（自然劣势）


    目的: 避免因子空间中的冗余方向，保持因子组合的独立性

    '
  icir_min_windows: 3
  icir_std_floor: 0.005
  strategy: keep_higher_ic
  threshold: 0.8
description: "当前无必选因子配置。可根据策略需要添加。\n\n示例 (若需要):\n  required_factors:\n    - 'MOM_20D'\
  \        # 必选: 动量因子\n    - 'RET_VOL_20D'    # 必选: 波动率因子\n"
family_quota:
  correlation:
    description: 相关性类因子最多选 1 个
    factors:
    - PV_CORR_20D
    max_count: 1
  momentum:
    description: 动量类因子最多选 1 个 (避免同向冗余)
    factors:
    - MOM_20D
    - SLOPE_20D
    max_count: 1
  price_features:
    description: 价格特征类最多选 1 个 (长短周期择一)
    factors:
    - PRICE_POSITION_20D
    - PRICE_POSITION_120D
    max_count: 1
  risk_adjusted:
    description: 风险调整类因子最多选 1 个
    factors:
    - MAX_DD_60D
    max_count: 1
  technical:
    description: 技术指标类最多选 1 个
    factors:
    - RSI_14
    max_count: 1
  volatility:
    description: 波动率类因子最多选 2 个 (覆盖不同周期)
    factors:
    - RET_VOL_20D
    - VOL_RATIO_20D
    - VOL_RATIO_60D
    max_count: 2
meta_factor_weighting:
  beta: 0.3
  enabled: true
  min_windows: 5
  mode: icir
  std_floor: 0.005
  windows: 20
metadata:
  created_date: '2025-10-26'
  description: ETF 轮动因子筛选系统 Step 5 约束配置
  last_modified: '2025-10-26'
  total_constraints: 5
  total_factors: 10
  version: '1.0'
minimum_ic:
  description: '全局最小IC要求: 0.02


    因子筛选逻辑:

    1. 首先按 IC > global_minimum 过滤候选因子

    2. 再应用家族配额、互斥对等约束

    3. 最后从满足条件的候选中按IC排序选择


    注: 该阈值可在 WFO 配置中覆盖 (是下界)

    '
  global_minimum: 0.02
mutual_exclusivity:
- pair:
  - PRICE_POSITION_20D
  - PRICE_POSITION_120D
  reason: 不同周期的价格位置指标功能重叠，选择周期最相关的一个
  severity: hard
- pair:
  - MOM_20D
  - SLOPE_20D
  reason: 动量和斜率反映相同的趋势特征，选择IC最高的一个
  severity: hard
- pair:
  - VOL_RATIO_20D
  - VOL_RATIO_60D
  reason: 不同周期的波动率比，若两者IC都高则选择回测表现更好的
  severity: soft
required_factors: []
validation:
  generate_report: true
  report_include:
  - candidate_factors
  - applied_constraints
  - constraint_impacts
  - final_selection
  - selection_reasons
  validate_config: true
