# 市场状态检测器配置 | Market Regime Detector
# 目标：在不引入前向展望偏差的前提下，基于趋势/波动/广度三维度判定 BULL/BEAR/RANGE

market_regime_detector:
  enabled: false  # ⚠️ 默认关闭，等Stage 2实现检测器类后再启用

  # 趋势维度（使用均线交叉的相对偏离百分比）
  trend:
    ma_short: 20                # 短期均线周期
    ma_long: 60                 # 长期均线周期
    bull_threshold: 2.0         # (%) 短均线上穿长均线超过 +2% 视为上升
    bear_threshold: -2.0        # (%) 短均线下穿长均线超过 -2% 视为下降

  # 波动维度（滚动标准差年化）
  volatility:
    window: 20                  # 20日滚动
    annualize: true             # 是否年化
    high_vol_threshold: 0.25    # >25% 判定为高波动（不利）
    low_vol_threshold: 0.15     # <15% 判定为低波动（有利）

  # 广度维度（ETF上涨占比）
  breadth:
    bull_threshold: 0.60        # >60% 上涨视为强势
    bear_threshold: 0.40        # <40% 上涨视为弱势

  # 状态判定规则（全部满足则命中，否则回退到RANGE）
  rules:
    bull_conditions:
      - "trend_score > bull_threshold"
      - "volatility < low_vol_threshold"
      - "breadth > bull_threshold"
    bear_conditions:
      - "trend_score < bear_threshold"
      - "volatility > high_vol_threshold"
      - "breadth < bear_threshold"
    range_conditions:
      - "else"

  # 置信度计算
  confidence:
    method: "score_based"      # 根据三个维度接近程度计算 [0,1]
    min_confidence: 0.5         # 最低置信度（低于则不建议放大/缩小仓位）

  # 实施建议（供仓位管理模块参考，不由检测器强制执行）
  sizing_guidance:
    multipliers:
      BULL: 1.2
      BEAR: 0.6
      RANGE: 0.9
    clamp: [0.5, 1.5]           # 最终乘子约束（与其他风控共同作用）
