# WFO参数网格配置
# 用于批量实验，测试不同参数组合的表现

# ============================================================================
# 基础参数网格 - 快速测试（2×2×2×2 = 16个实验）
# ============================================================================
basic_grid:
  is_period: [252, 504]          # 样本内天数: 1年, 2年
  oos_period: [60, 120]          # 样本外天数: 3个月, 6个月
  step_size: [20, 40]            # 滚动步长: 月度, 双月度
  target_factor_count: [5, 8]    # 因子数: 中等, 较多

# ============================================================================
# 完整参数网格 - 详细测试（3×3×3×3 = 81个实验）
# ============================================================================
full_grid:
  is_period: [126, 252, 504]           # 样本内: 半年, 1年, 2年
  oos_period: [30, 60, 120]            # 样本外: 1.5月, 3月, 6月
  step_size: [10, 20, 40]              # 滚动步长: 半月, 月, 双月
  target_factor_count: [3, 5, 8]       # 因子数: 少, 中, 多

# ============================================================================
# 保守策略 - 单一实验
# ============================================================================
conservative:
  is_period: [504]      # 2年样本内
  oos_period: [120]     # 6个月样本外
  step_size: [40]       # 双月滚动
  target_factor_count: [3]  # 只选3个因子

# ============================================================================
# 激进策略 - 单一实验
# ============================================================================
aggressive:
  is_period: [126]      # 半年样本内
  oos_period: [30]      # 1.5月样本外
  step_size: [10]       # 半月滚动
  target_factor_count: [8]  # 选8个因子

# ============================================================================
# 焦点测试 - IS周期影响（固定其他参数）
# ============================================================================
test_is_period:
  is_period: [126, 189, 252, 315, 378, 441, 504]  # 0.5年~2年，每次+3个月
  oos_period: [60]                                 # 固定3个月
  step_size: [20]                                  # 固定月度
  target_factor_count: [5]                         # 固定5因子

# ============================================================================
# 焦点测试 - OOS周期影响（固定其他参数）
# ============================================================================
test_oos_period:
  is_period: [252]                     # 固定1年
  oos_period: [20, 40, 60, 90, 120]    # 1月~6月
  step_size: [20]                      # 固定月度
  target_factor_count: [5]             # 固定5因子

# ============================================================================
# 焦点测试 - 因子数影响（固定其他参数）
# ============================================================================
test_factor_count:
  is_period: [252]                      # 固定1年
  oos_period: [60]                      # 固定3个月
  step_size: [20]                       # 固定月度
  target_factor_count: [2, 3, 4, 5, 6, 7, 8, 9, 10]  # 2~10因子

# ============================================================================
# 使用示例
# ============================================================================
# 1. 快速测试:
#    python scripts/wfo_experiments.py --grid basic_grid
#
# 2. 详细测试:
#    python scripts/wfo_experiments.py --grid full_grid
#
# 3. 单一策略:
#    python scripts/wfo_experiments.py --grid conservative
#
# 4. 焦点测试:
#    python scripts/wfo_experiments.py --grid test_is_period
