# Factor Engine配置

cache:
  memory_size_mb: 500  # 内存缓存大小(MB)
  disk_cache_dir: "cache/factor_engine"  # 磁盘缓存目录
  ttl_hours: 24  # 缓存有效期(小时)
  enable_disk: true  # 启用磁盘缓存
  enable_memory: true  # 启用内存缓存

data_provider:
  type: "parquet"  # 数据提供者类型
  raw_data_dir: "raw"  # 原始数据目录

registry:
  registry_file: "factor_system/research/metadata/factor_registry.json"  # 注册表文件

logging:
  level: "INFO"  # 日志级别
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"


