# ETF轮动VBT回测配置文件
# 通过修改此文件来调整回测参数，无需改动代码

# === 数据路径配置 ===
data_paths:
  panel_file: "/Users/zhangshenshen/深度量化0927/etf_rotation_system/data/results/panels/panel_20251020_104106/panel.parquet"
  price_dir: "/Users/zhangshenshen/深度量化0927/raw/ETF/daily"
  screening_file: "/Users/zhangshenshen/深度量化0927/etf_rotation_system/data/results/screening/screening_20251020_104628/passed_factors.csv"
  output_dir: "/Users/zhangshenshen/深度量化0927/etf_rotation_system/data/results/backtest"

# === 因子配置 ===
factor_config:
  top_k: 8                     # 使用筛选出的前8个因子
  factors: ['PRICE_POSITION_60D', 'MOM_ACCEL', 'VOLATILITY_120D', 'VOL_VOLATILITY_20', 'VOLUME_PRICE_TREND', 'RSI_6', 'INTRADAY_POSITION', 'INTRA_DAY_RANGE']  # 指定8个有效因子

# === 回测参数配置 ===
backtest_config:
  top_n_list: [3, 5, 8, 10]   # Top-N候选列表
  rebalance_freq: 20           # 调仓频率（交易日）
  fees: 0.001                  # 交易费用率
  init_cash: 1000000          # 初始资金

# === 权重网格配置 ===
weight_grid:
  # 权重网格点 - 支持自定义权重范围
  grid_points: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]  # 权重网格点 (9^8 = 4300万组合，需要限制)
  weight_sum_range: [0.8, 1.2]                           # 权重和的有效范围（更严格过滤）
  max_combinations: 50000                                # 最大组合数限制 (5万组合)

# === 复合因子计算配置 ===
composite_config:
  standardization_method: "zscore"    # 标准化方法: "zscore" 或 "rank"
  enable_score_cache: true           # 是否启用得分缓存（提高性能）

# === 性能优化配置 ===
performance_config:
  # 线程配置（VectorBT优化）
  omp_num_threads: 2
  veclib_maximum_threads: 2
  mkl_num_threads: 2

  # 批处理配置
  batch_size: 1000                 # 批处理大小
  enable_progress_bar: true        # 是否显示进度条

# === 输出配置 ===
output_config:
  save_top_results: 50            # 保存前N个结果
  save_best_config: true          # 是否保存最优配置
  save_detailed_results: true     # 是否保存详细结果

  # 结果文件命名
  results_prefix: "backtest_results"
  best_config_prefix: "best_strategy"

# === 调试和日志配置 ===
debug_config:
  verbose: false                  # 详细输出模式
  log_errors: true               # 记录错误日志
  save_intermediate: false       # 保存中间结果

# === 回测约束配置 ===
constraints:
  min_trade_days: 252           # 最少交易日数
  max_single_weight: 0.8         # 单个因子最大权重
  min_effective_symbols: 3      # 最少有效ETF数量

# === 策略评估指标配置 ===
metrics:
  # 主要排序指标
  primary_metric: "sharpe_ratio"  # 主要排序指标: "sharpe_ratio", "total_return", "max_drawdown"

  # 风险指标计算
  periods_per_year: 252          # 年化交易天数

  # 报告阈值
  min_sharpe_ratio: 0.5          # 最小夏普比率阈值
  max_drawdown_threshold: -30    # 最大回撤阈值（百分比）

# === 场景预设配置 ===
# 可以定义多个预设场景，方便切换
presets:
  # 快速测试场景
  quick_test:
    weight_grid:
      grid_points: [0.0, 0.5, 1.0]
      max_combinations: 100
    backtest_config:
      top_n_list: [3, 5]
    output_config:
      save_top_results: 10

  # 标准回测场景
  standard:
    weight_grid:
      grid_points: [0.0, 0.25, 0.5, 0.75, 1.0]
      max_combinations: 1000
    backtest_config:
      top_n_list: [3, 5, 8]

  # 全面优化场景 - 8因子万级组合 (内存安全版)
  comprehensive:
    weight_grid:
      grid_points: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
      max_combinations: 50000               # 5万组合 (内存安全)
      weight_sum_range: [0.8, 1.2]
    backtest_config:
      top_n_list: [3, 5, 8]                 # 专注于有效的Top-N配置
    performance_config:
      omp_num_threads: 4                    # 限制并行度 (2GB内存/线程 ≈ 6GB)
      veclib_maximum_threads: 4
      mkl_num_threads: 4
      batch_size: 1000                      # 减小批处理大小
      enable_progress_bar: true
    memory_config:
      enable_gc: true                       # 启用垃圾回收
      checkpoint_interval: 10000            # 每1万组合保存一次
      max_memory_usage_gb: 18               # 最大内存使用限制

# 当前使用的预设（可选）
current_preset: "comprehensive"