# ETF轮动精细回测配置文件
# 基于暴力回测结果的精细优化配置

# === 数据路径配置 ===
data_paths:
  panel_file: "/Users/zhangshenshen/深度量化0927/etf_rotation_system/data/results/panels/panel_20251020_162504/panel.parquet"
  price_dir: "/Users/zhangshenshen/深度量化0927/raw/ETF/daily"
  screening_file: "/Users/zhangshenshen/深度量化0927/etf_rotation_system/data/results/screening/screening_20251020_104628/passed_factors.csv"
  output_dir: "/Users/zhangshenshen/深度量化0927/etf_rotation_system/data/results/backtest"

# === 精细回测配置 ===
fine_grained_config:
  enable_fine_grained: true           # 启用精细优化模式
  base_on_analysis: true              # 基于分析结果优化

# === 核心因子配置 ===
core_factors:
  # 基于暴力回测识别的核心因子
  primary_factors:
    - name: "RSI_6"
      weight_range: [0.35, 0.50]      # 基于统计分析的最优范围
      importance: 1.0                  # 重要性权重
      description: "短期相对强弱指标"

    - name: "VOL_VOLATILITY_20"
      weight_range: [0.20, 0.30]
      importance: 0.9
      description: "成交量波动率因子"

    - name: "VOLATILITY_120D"
      weight_range: [0.10, 0.20]
      importance: 0.8
      description: "长期价格波动率因子"

    - name: "INTRADAY_POSITION"
      weight_range: [0.15, 0.25]
      importance: 0.7
      description: "日内位置因子"

  # 补充因子
  supplementary_factors:
    - name: "VOLUME_PRICE_TREND"
      weight_range: [0.05, 0.15]
      importance: 0.6
      description: "量价趋势因子"

# === 精细权重网格配置 ===
fine_weight_grid:
  # 核心因子精细网格
  core_grid_points: [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]

  # 补充因子网格（更精细）
  supplementary_grid_points: [0.0, 0.05, 0.1, 0.15, 0.2]

  # 权重约束
  weight_sum_range: [0.9, 1.1]
  max_single_weight: 0.6          # 单个因子最大权重

  # 约束优化
  enforce_sum_to_one: true        # 强制权重和为1
  allow_negative_weights: false   # 不允许负权重

# === 策略模板配置 ===
strategy_templates:
  core_strategy:
    name: "核心因子策略"
    description: "聚焦4个核心因子，追求最高夏普比率"
    target_sharpe: 0.48
    risk_level: "medium"
    factors:
      RSI_6: 0.428
      VOL_VOLATILITY_20: 0.242
      VOLATILITY_120D: 0.134
      INTRADAY_POSITION: 0.196

  balanced_strategy:
    name: "平衡策略"
    description: "结合核心和补充因子，平衡风险收益"
    target_sharpe: 0.47
    risk_level: "medium_low"
    factors:
      RSI_6: 0.424
      VOL_VOLATILITY_20: 0.184
      VOLATILITY_120D: 0.108
      INTRADAY_POSITION: 0.170
      VOLUME_PRICE_TREND: 0.115

  conservative_strategy:
    name: "保守策略"
    description: "使用最稳定的2个因子，控制回撤风险"
    target_sharpe: 0.46
    risk_level: "low"
    factors:
      VOLATILITY_120D: 0.500
      VOL_VOLATILITY_20: 0.500

# === 优化目标配置 ===
optimization_objectives:
  primary_objective: "sharpe_ratio"    # 主要优化目标
  secondary_objectives:                # 次要优化目标
    - "total_return"
    - "max_drawdown"

  # 多目标优化权重
  objective_weights:
    sharpe_ratio: 0.6
    total_return: 0.3
    max_drawdown: 0.1

# === 约束条件配置 ===
constraints:
  # 基本约束
  min_effective_factors: 2            # 最少有效因子数
  max_effective_factors: 5            # 最多有效因子数

  # 性能约束
  min_sharpe_ratio: 0.45              # 最小夏普比率要求
  max_drawdown_threshold: -50         # 最大回撤阈值
  min_total_return: 40                # 最小总收益要求

  # 稳定性约束
  factor_stability_threshold: 0.7     # 因子稳定性阈值
  correlation_limit: 0.8              # 因子相关性上限

# === 搜索策略配置 ===
search_strategy:
  # 搜索方法
  search_method: "adaptive_grid"       # 自适应网格搜索
  refinement_method: "local_search"    # 局部搜索精炼

  # 搜索参数
  max_iterations: 5000                # 最大迭代次数
  convergence_threshold: 1e-6         # 收敛阈值
  early_stopping_patience: 100        # 早停耐心值

# === 性能优化配置 ===
performance_config:
  # 并行计算
  n_workers: 8                         # 工作进程数
  chunk_size: 50                       # 块大小
  enable_cache: true                   # 启用缓存

  # 内存管理
  max_memory_usage_gb: 12.0            # 最大内存使用
  enable_gc: true                      # 启用垃圾回收
  checkpoint_interval: 1000            # 检查点间隔

# === 输出配置 ===
output_config:
  # 结果保存
  save_optimization_history: true      # 保存优化历史
  save_intermediate_results: true      # 保存中间结果
  save_factor_analysis: true           # 保存因子分析

  # 结果文件命名
  results_prefix: "fine_grained_results"
  optimization_prefix: "fine_optimization"

  # 报告生成
  generate_performance_report: true    # 生成性能报告
  generate_factor_report: true         # 生成因子报告
  include_visualizations: true         # 包含可视化图表

# === 验证配置 ===
validation_config:
  # 时间窗口验证
  enable_time_window_validation: true  # 启用时间窗口验证
  validation_windows:                 # 验证窗口
    - start_date: "2023-01-01"
      end_date: "2023-12-31"
    - start_date: "2024-01-01"
      end_date: "2024-12-31"

  # 样本外验证
  enable_out_of_sample_test: true      # 启用样本外测试
  out_of_sample_ratio: 0.2             # 样本外比例

# === 调试配置 ===
debug_config:
  verbose: false                       # 详细输出
  log_level: "INFO"                    # 日志级别
  save_debug_info: false               # 保存调试信息
  profile_performance: false           # 性能分析

# === 高级优化配置 ===
advanced_config:
  # 贝叶斯优化（可选）
  enable_bayesian_optimization: false
  bayesian_iterations: 200
  acquisition_function: "ei"           # 期望改进函数

  # 遗传算法（可选）
  enable_genetic_algorithm: false
  population_size: 100
  generations: 50
  mutation_rate: 0.1
  crossover_rate: 0.8

# === 风险管理配置 ===
risk_management:
  # 组合风险控制
  enable_risk_parity: false            # 启用风险平价
  max_portfolio_volatility: 0.15       # 最大组合波动率

  # 回撤控制
  max_drawdown_limit: -0.35            # 最大回撤限制
  drawdown_recovery_target: 1.1        # 回撤恢复目标

# === 当前优化策略 ===
current_optimization:
  # 默认使用核心策略进行精细优化
  strategy_type: "core_strategy"
  optimization_level: "fine"           # 精细优化级别

  # 搜索空间定义
  search_space:
    RSI_6: [0.35, 0.45, 0.5]
    VOL_VOLATILITY_20: [0.2, 0.25, 0.3]
    VOLATILITY_120D: [0.1, 0.15, 0.2]
    INTRADAY_POSITION: [0.15, 0.2, 0.25]
    VOLUME_PRICE_TREND: [0.0, 0.05, 0.1]