data_paths:
  panel_file: /Users/zhangshenshen/深度量化0927/etf_rotation_system/data/results/panels/panel_20251022_155341/panel.parquet
  price_dir: /Users/zhangshenshen/深度量化0927/raw/ETF/daily
  screening_file: /Users/zhangshenshen/深度量化0927/etf_rotation_system/data/results/screening/screening_20251022_155407/passed_factors.csv
  output_dir: /Users/zhangshenshen/深度量化0927/etf_rotation_system/data/results/backtest
parallel_config:
  n_workers: 9
  chunk_size: 20
  enable_cache: true
  log_level: INFO
factor_config:
  top_k: 15
  factors: []
backtest_config:
  top_n_list:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  rebalance_freq_list:
  - 3
  - 5
  - 8
  - 10
  - 13
  - 18
  - 25
  fees: 0.001
  init_cash: 1000000
weight_grid:
  grid_points:
  - 0.0
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 1.0
  weight_sum_range:
  - 0.8
  - 1.2
  max_combinations: 10000
composite_config:
  standardization_method: zscore
  enable_score_cache: true
  numerical_epsilon: 1e-8
vectorization_config:
  max_memory_usage_gb: 16.0
  enable_gc: true
  checkpoint_interval: 5000
  use_float32: false
  batch_processing_size: 1000
performance_config:
  omp_num_threads: 1
batch_config:
  enable_batch_mode: false
  batch_by: rebalance_freq
  current_batch: null
  save_intermediate: true
  veclib_maximum_threads: 1
  mkl_num_threads: 1
  enable_progress_bar: true
output_config:
  save_top_results: 200
  save_best_config: true
  save_detailed_results: true
  results_prefix: parallel_backtest_results
  best_config_prefix: parallel_best_strategy
debug_config:
  verbose: false
  log_errors: true
  save_intermediate: false
constraints:
  min_trade_days: 252
  max_single_weight: 0.8
  min_effective_symbols: 3
metrics:
  primary_metric: sharpe_ratio
  periods_per_year: 252
  min_sharpe_ratio: 0.5
  max_drawdown_threshold: -30
presets:
  quick_test:
    weight_grid:
      grid_points:
      - 0.0
      - 0.5
      - 1.0
      max_combinations: 100
    backtest_config:
      top_n_list:
      - 3
      - 5
    parallel_config:
      n_workers: 3
      chunk_size: 10
    output_config:
      save_top_results: 10
  standard:
    weight_grid:
      grid_points:
      - 0.0
      - 0.25
      - 0.5
      - 0.75
      - 1.0
      max_combinations: 1000
      weight_sum_range:
      - 0.9
      - 1.1
    backtest_config:
      top_n_list:
      - 3
      - 5
      - 8
    parallel_config:
      n_workers: 6
      chunk_size: 15
  high_performance:
    weight_grid:
      grid_points:
      - 0.0
      - 0.05
      - 0.1
      - 0.15
      - 0.2
      - 0.25
      - 0.3
      - 0.35
      - 0.4
      - 0.45
      - 0.5
      - 0.55
      - 0.6
      - 0.65
      - 0.7
      - 0.75
      - 0.8
      - 0.85
      - 0.9
      - 0.95
      - 1.0
      max_combinations: 20000
      weight_sum_range:
      - 0.7
      - 1.3
    backtest_config:
      top_n_list:
      - 3
      - 5
      - 8
    parallel_config:
      n_workers: 12
      chunk_size: 30
    vectorization_config:
      max_memory_usage_gb: 24.0
      checkpoint_interval: 10000
  memory_safe:
    weight_grid:
      grid_points:
      - 0.0
      - 0.2
      - 0.4
      - 0.6
      - 0.8
      - 1.0
      max_combinations: 5000
      weight_sum_range:
      - 0.9
      - 1.1
    backtest_config:
      top_n_list:
      - 3
      - 5
      - 8
    parallel_config:
      n_workers: 6
      chunk_size: 25
    vectorization_config:
      max_memory_usage_gb: 8.0
      enable_gc: true
      checkpoint_interval: 2000
  fine_grid:
    weight_grid:
      grid_points:
      - 0.0
      - 0.05
      - 0.1
      - 0.15
      - 0.2
      - 0.25
      - 0.3
      - 0.35
      - 0.4
      - 0.45
      - 0.5
      - 0.55
      - 0.6
      - 0.65
      - 0.7
      - 0.75
      - 0.8
      - 0.85
      - 0.9
      - 0.95
      - 1.0
      max_combinations: 15000
      weight_sum_range:
      - 0.75
      - 1.25
    backtest_config:
      top_n_list:
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    parallel_config:
      n_workers: 8
      chunk_size: 18
  vectorized_optimized:
    weight_grid:
      grid_points:
      - 0.0
      - 0.25
      - 0.5
      - 0.75
      - 1.0
      max_combinations: 10000
    backtest_config:
      top_n_list:
      - 3
      - 5
      - 8
    vectorization_config:
      max_memory_usage_gb: 20.0
      enable_gc: true
      use_float32: false
      batch_processing_size: 2000
