# 0700.HK 多时间框架批量筛选配置
# BatchConfig 结构
batch_name: "0700_HK_multi_timeframe_analysis"
description: "腾讯控股全时间框架因子分析"
max_concurrent_tasks: 2
continue_on_error: true
generate_summary_report: true
compare_results: true
max_retries: 2

screening_configs:
  - name: "0700_HK_5min"
    description: "腾讯控股5分钟因子筛选"
    symbols: ["0700.HK"]
    timeframes: ["5min"]
    ic_horizons: [1, 3, 5, 10, 20]
    min_sample_size: 150
    alpha_level: 0.05
    fdr_method: "benjamini_hochberg"
    rolling_window: 120
    min_ic_threshold: 0.015
    min_ir_threshold: 0.3
    min_stability_threshold: 0.6
    min_robustness_score: 0.6
    vif_threshold: 5.0
    correlation_threshold: 0.7
    commission_rate: 0.002
    slippage_bps: 5.0
    market_impact_coeff: 0.1
    max_vif_threshold: 10.0
    max_cost_threshold: 0.01
    weights:
      predictive_power: 0.35
      stability: 0.25
      independence: 0.20
      practicality: 0.10
      short_term_fitness: 0.10
    max_workers: 6
    enable_parallel: true
    save_reports: true
    save_detailed_metrics: true
    data_root: "../因子输出"
    output_dir: "./因子筛选"
    log_level: "INFO"
    memory_limit_gb: 8.0
    timeout_minutes: 30

  - name: "0700_HK_15min"
    description: "腾讯控股15分钟因子筛选"
    symbols: ["0700.HK"]
    timeframes: ["15min"]
    ic_horizons: [1, 3, 5, 10, 20]
    min_sample_size: 150
    alpha_level: 0.05
    fdr_method: "benjamini_hochberg"
    rolling_window: 120
    min_ic_threshold: 0.015
    min_ir_threshold: 0.3
    min_stability_threshold: 0.6
    min_robustness_score: 0.6
    vif_threshold: 5.0
    correlation_threshold: 0.7
    commission_rate: 0.002
    slippage_bps: 5.0
    market_impact_coeff: 0.1
    max_vif_threshold: 10.0
    max_cost_threshold: 0.01
    weights:
      predictive_power: 0.35
      stability: 0.25
      independence: 0.20
      practicality: 0.10
      short_term_fitness: 0.10
    max_workers: 6
    enable_parallel: true
    save_reports: true
    save_detailed_metrics: true
    data_root: "../因子输出"
    output_dir: "./因子筛选"
    log_level: "INFO"
    memory_limit_gb: 8.0
    timeout_minutes: 30

  - name: "0700_HK_60min"
    description: "腾讯控股60分钟因子筛选"
    symbols: ["0700.HK"]
    timeframes: ["60min"]
    ic_horizons: [1, 3, 5, 10, 20]
    min_sample_size: 150
    alpha_level: 0.05
    fdr_method: "benjamini_hochberg"
    rolling_window: 120
    min_ic_threshold: 0.015
    min_ir_threshold: 0.3
    min_stability_threshold: 0.6
    min_robustness_score: 0.6
    vif_threshold: 5.0
    correlation_threshold: 0.7
    commission_rate: 0.002
    slippage_bps: 5.0
    market_impact_coeff: 0.1
    max_vif_threshold: 10.0
    max_cost_threshold: 0.01
    weights:
      predictive_power: 0.35
      stability: 0.25
      independence: 0.20
      practicality: 0.10
      short_term_fitness: 0.10
    max_workers: 6
    enable_parallel: true
    save_reports: true
    save_detailed_metrics: true
    data_root: "../因子输出"
    output_dir: "./因子筛选"
    log_level: "INFO"
    memory_limit_gb: 8.0
    timeout_minutes: 30

  - name: "0700_HK_30min"
    description: "腾讯控股30分钟因子筛选"
    symbols: ["0700.HK"]
    timeframes: ["30min"]
    ic_horizons: [1, 3, 5, 10, 20]
    min_sample_size: 150
    alpha_level: 0.05
    fdr_method: "benjamini_hochberg"
    rolling_window: 120
    min_ic_threshold: 0.015
    min_ir_threshold: 0.3
    min_stability_threshold: 0.6
    min_robustness_score: 0.6
    vif_threshold: 5.0
    correlation_threshold: 0.7
    commission_rate: 0.002
    slippage_bps: 5.0
    market_impact_coeff: 0.1
    max_vif_threshold: 10.0
    max_cost_threshold: 0.01
    weights:
      predictive_power: 0.35
      stability: 0.25
      independence: 0.20
      practicality: 0.10
      short_term_fitness: 0.10
    max_workers: 6
    enable_parallel: true
    save_reports: true
    save_detailed_metrics: true
    data_root: "../因子输出"
    output_dir: "./因子筛选"
    log_level: "INFO"
    memory_limit_gb: 8.0
    timeout_minutes: 30

  - name: "0700_HK_daily"
    description: "腾讯控股日线因子筛选"
    symbols: ["0700.HK"]
    timeframes: ["daily"]
    ic_horizons: [1, 3, 5, 10, 20]
    min_sample_size: 150
    alpha_level: 0.05
    fdr_method: "benjamini_hochberg"
    rolling_window: 120
    min_ic_threshold: 0.015
    min_ir_threshold: 0.3
    min_stability_threshold: 0.6
    min_robustness_score: 0.6
    vif_threshold: 5.0
    correlation_threshold: 0.7
    commission_rate: 0.002
    slippage_bps: 5.0
    market_impact_coeff: 0.1
    max_vif_threshold: 10.0
    max_cost_threshold: 0.01
    weights:
      predictive_power: 0.35
      stability: 0.25
      independence: 0.20
      practicality: 0.10
      short_term_fitness: 0.10
    max_workers: 6
    enable_parallel: true
    save_reports: true
    save_detailed_metrics: true
    data_root: "../因子输出"
    output_dir: "./因子筛选"
    log_level: "INFO"
    memory_limit_gb: 8.0
    timeout_minutes: 30

# 全局设置
global_data_root: "../因子输出"
global_output_dir: "./因子筛选"
