# 批量因子筛选配置
# 支持HK/US多市场、多股票、多时间框架的批量筛选

name: "multi_market_batch_screening"
description: "HK/US多市场批量因子筛选 - 支持88只股票 × 10个时间框架 - 公平评分集成"
version: "3.0.0"

# ================== 市场和股票配置 ==================

# 市场选择
markets:
  - "HK"
  - "US"

# 股票选择
# - null: 处理所有可用股票
# - ["0700.HK", "0005.HK"]: 处理指定股票列表
symbols: null

# 排除股票列表
exclude_symbols: []

# ================== 时间框架配置 ==================

# 完整时间框架列表（10个）
timeframes:
  - "1min"
  - "2min"
  - "3min"
  - "5min"
  - "15min"
  - "30min"
  - "60min"
  - "2h"
  - "4h"
  - "1day"

# 时间框架筛选（可选）
# enabled_timeframe_groups: ["short", "medium", "long"]
# 分组定义：
#   ultra_short: 1min, 2min, 3min
#   short: 5min, 15min, 30min
#   medium: 60min, 2h, 4h
#   long: 1day

# ================== 数据路径配置 ==================

# 因子数据根目录（使用相对路径，提升可移植性）
data_root: "factor_system/factor_output"

# 价格数据根目录（废弃，使用data_root）
raw_data_root: ""  # @deprecated 使用data_root替代

# 批量筛选结果输出目录
output_root: "./batch_screening_results"

# 日志目录
log_root: "./logs/batch_screening"

# 缓存目录
cache_root: "./cache/batch"

# ================== IC分析配置 ==================

# IC分析周期（收益预测周期）
ic_horizons: [1, 3, 5, 10, 20]

# 最小样本数量
min_sample_size: 100

# 显著性水平
alpha_level: 0.05

# FDR校正方法
fdr_method: "benjamini_hochberg"

# ================== 稳定性配置 ==================

# 滚动窗口大小（用于稳定性分析）
rolling_window: 60

# IC阈值
min_ic_threshold: 0.015

# IR阈值（信息比率）
min_ir_threshold: 0.35

# 稳健性得分阈值
min_robustness_score: 0.6

# ================== 独立性配置 ==================

# VIF阈值（方差膨胀因子）
vif_threshold: 5.0

# 相关系数阈值
correlation_threshold: 0.8

# ================== 交易成本配置 ==================

# 佣金费率
commission_rate: 0.002

# 滑点（基点）
slippage_bps: 5.0

# 市场冲击系数
market_impact_coeff: 0.1

# ================== 筛选阈值 ==================

# 稳定性最小阈值
min_stability_threshold: 0.6

# VIF最大阈值
max_vif_threshold: 10.0

# 成本最大阈值
max_cost_threshold: 0.01

# ================== 权重配置 ==================

# 五维度权重配置
weights:
  predictive_power: 0.35    # 预测能力
  stability: 0.25           # 稳定性
  independence: 0.20        # 独立性
  practicality: 0.10        # 实用性
  short_term_fitness: 0.10  # 短周期适应性

# ================== 公平评分配置 ==================

# 启用公平评分系统 (v3.0.0新增)
enable_fair_scoring: true

# 公平评分参数
fair_scoring:
  # 统计功效归一化
  enable_statistical_power_normalization: true

  # 长周期经济意义奖励
  enable_long_term_reward: true

  # 样本量不确定性补偿
  enable_sample_size_uncertainty_penalty: true

  # 时间框架调整系数
  timeframe_adjustments:
    "1min": 0.85    # 短周期轻微惩罚
    "5min": 1.00    # 基准
    "15min": 1.05   # 中短周期轻微奖励
    "30min": 1.08   # 中周期奖励
    "60min": 1.12   # 中长周期奖励
    "2h": 1.18      # 长周期奖励
    "4h": 1.25      # 长周期强奖励
    "1day": 1.35    # 日线强奖励

  # 统计功效参数
  statistical_power:
    base_sample_size: 1000     # 基准样本量
    power_threshold: 0.8       # 功效阈值
    significance_level: 0.05   # 显著性水平

  # 样本量不确定性参数
  sample_size_uncertainty:
    small_sample_threshold: 500    # 小样本阈值
    uncertainty_factor: 0.1        # 不确定性因子
    penalty_strength: 0.15         # 惩罚强度

# ================== 批量处理配置 ==================

# 最大并行股票数
max_parallel_stocks: 4

# 批处理大小（每批处理的股票数量，用于内存管理）
batch_size: 10

# 进度保存间隔（每处理N只股票保存一次）
checkpoint_interval: 5

# ================== 输出配置 ==================

# 保存单只股票的详细报告
save_individual_reports: true

# 保存批量汇总报告
save_summary_report: true

# 保存跨股票因子排名
save_cross_stock_ranking: true

# 保存市场级别统计
save_market_summary: true

# 输出格式
output_formats:
  - "csv"      # CSV格式（Excel兼容）
  - "json"     # JSON格式（程序读取）
  - "markdown" # Markdown格式（文档查看）

# ================== 性能配置 ==================

# 内存限制（GB）
memory_limit_gb: 8.0

# 单只股票超时时间（分钟）
timeout_per_stock_minutes: 10

# 总超时时间（小时）
timeout_total_hours: 4

# 启用内存优化
enable_memory_optimization: true

# 启用结果缓存
enable_result_caching: true

# ================== 日志配置 ==================

# 日志级别
log_level: "INFO"

# 详细模式
verbose: true

# 进度条显示
show_progress_bar: true

# ================== 错误处理配置 ==================

# 单只股票失败时是否继续
continue_on_error: true

# 最大失败次数（超过则终止）
max_failures: 10

# 失败重试次数
retry_count: 2

# ================== 高级配置 ==================

# 启用断点续传
enable_checkpoint: true

# 启用并行处理
enable_parallel: true

# 启用自动清理旧结果
auto_cleanup_old_results: false

# 保留最近N天的结果
results_retention_days: 30

# ================== 筛选策略配置 ==================

# 筛选模式
# - "conservative": 保守模式，严格筛选
# - "balanced": 平衡模式，适中筛选
# - "aggressive": 激进模式，宽松筛选
screening_mode: "balanced"

# 模式预设
screening_presets:
  conservative:
    min_ic_threshold: 0.02
    min_ir_threshold: 0.5
    min_robustness_score: 0.7
    vif_threshold: 3.0
  
  balanced:
    min_ic_threshold: 0.015
    min_ir_threshold: 0.35
    min_robustness_score: 0.6
    vif_threshold: 5.0
  
  aggressive:
    min_ic_threshold: 0.01
    min_ir_threshold: 0.25
    min_robustness_score: 0.5
    vif_threshold: 8.0

