name: "complete_multi_tf_screening"
description: "完整多时间框架筛选配置 - 无需命令行参数"

# 股票和时间框架配置
symbols: ["0700.HK"]
timeframes: ["5min", "15min", "30min", "60min", "daily"]

# 数据配置 - 预设路径
data_root: "../因子输出"
raw_data_root: "../raw"
output_dir: "./因子筛选"

# IC分析配置
ic_horizons: [1, 3, 5, 10, 20]
min_sample_size: 100
alpha_level: 0.05
fdr_method: "benjamini_hochberg"

# 稳定性配置
rolling_window: 60
min_ic_threshold: 0.015
min_ir_threshold: 0.35
min_robustness_score: 0.6

# 独立性配置
vif_threshold: 5.0
correlation_threshold: 0.8

# 交易成本参数
commission_rate: 0.002
slippage_bps: 5.0
market_impact_coeff: 0.1

# 筛选阈值
min_stability_threshold: 0.6
max_vif_threshold: 10.0
max_cost_threshold: 0.01

# 权重配置
weights:
  predictive_power: 0.35
  stability: 0.25
  independence: 0.20
  practicality: 0.10
  short_term_fitness: 0.10

# 并行配置
max_workers: 4
enable_parallel: true

# 输出配置
save_reports: true
save_detailed_metrics: true
log_level: "INFO"

# 性能配置
memory_limit_gb: 8.0
timeout_minutes: 30
