# ETF因子引擎配置

# 数据配置
data:
  source_dir: "raw/ETF/daily"
  output_dir: "factor_output/etf_rotation"
  price_field: "close"  # 优先使用close，如有adj_close会自动映射

# 时间范围
timeframe:
  start_date: "20200102"
  end_date: "20251014"
  frequency: "daily"

# 因子计算
factors:
  engine_version: "1.0.0"
  compute_all: true
  
  # VBT指标
  vbt:
    enabled: true
    ma_windows: [5, 10, 20, 30, 40, 50, 60, 80, 100, 120, 150, 200, 252]
    ema_spans: [5, 10, 12, 20, 26, 30, 40, 50, 60, 80, 100, 120]
    rsi_windows: [6, 9, 12, 14, 20, 24, 30, 60]
    bb_windows: [10, 15, 20, 25, 30, 40, 50]
    bb_alphas: [1.5, 2.0, 2.5]
    atr_windows: [7, 10, 14, 20, 30, 60]
  
  # TA-Lib指标
  talib:
    enabled: true
    full_coverage: true
  
  # 自定义指标
  custom:
    enabled: true
    return_periods: [1, 2, 3, 5, 10, 20, 30, 60]
    volatility_windows: [5, 10, 20, 30, 60]

# 筛选配置
filtering:
  # 生产模式
  production:
    min_coverage: 0.80
    allow_zero_variance: false
    allow_leak_suspect: false
    deduplicate: true
  
  # 研究模式
  research:
    min_coverage: 0.30
    allow_zero_variance: true
    allow_leak_suspect: true
    deduplicate: true

# 诊断配置
diagnostics:
  coverage_threshold: 0.10
  correlation_threshold: 0.999
  temporal_samples: 5
