execution_info:
  python_version: 3.11.9
  system_info:
    architecture: 64bit
    platform: Darwin
    processor: arm
  timestamp: '2025-10-12T05:14:08.669785'
screening_parameters:
  adaptive_tier_thresholds:
    120min:
      tier1: 0.66
      tier2: 0.48
      tier3: 0.36
      upgrade_tier1: 0.6
      upgrade_tier2: 0.43
    15min:
      tier1: 0.72
      tier2: 0.55
      tier3: 0.42
      upgrade_tier1: 0.68
      upgrade_tier2: 0.51
    1day:
      tier1: 0.64
      tier2: 0.46
      tier3: 0.34
      upgrade_tier1: 0.57
      upgrade_tier2: 0.41
    1min:
      tier1: 0.8
      tier2: 0.7
      tier3: 0.55
      upgrade_tier1: 0.77
      upgrade_tier2: 0.65
    240min:
      tier1: 0.65
      tier2: 0.47
      tier3: 0.35
      upgrade_tier1: 0.58
      upgrade_tier2: 0.42
    2h:
      tier1: 0.66
      tier2: 0.48
      tier3: 0.36
      upgrade_tier1: 0.6
      upgrade_tier2: 0.43
    2min:
      tier1: 0.78
      tier2: 0.62
      tier3: 0.48
      upgrade_tier1: 0.75
      upgrade_tier2: 0.58
    30min:
      tier1: 0.7
      tier2: 0.52
      tier3: 0.4
      upgrade_tier1: 0.65
      upgrade_tier2: 0.48
    3min:
      tier1: 0.77
      tier2: 0.6
      tier3: 0.46
      upgrade_tier1: 0.73
      upgrade_tier2: 0.56
    4h:
      tier1: 0.65
      tier2: 0.47
      tier3: 0.35
      upgrade_tier1: 0.58
      upgrade_tier2: 0.42
    5min:
      tier1: 0.75
      tier2: 0.58
      tier3: 0.44
      upgrade_tier1: 0.71
      upgrade_tier2: 0.54
    60min:
      tier1: 0.68
      tier2: 0.5
      tier3: 0.38
      upgrade_tier1: 0.62
      upgrade_tier2: 0.45
  alignment_failure_strategy: warn
  alpha_level: 0.05
  base_factors:
  - MA5
  - MA10
  - RSI14
  - MACD_12_26_9
  cache_root: ''
  commission_rate: 0.002
  correlation_threshold: 0.8
  data_root: /Users/zhangshenshen/深度量化0927/factor_system/factor_output
  description: 默认筛选配置
  enable_legacy_format: false
  enable_parallel: true
  enable_timeframe_adaptive: true
  factor_change_threshold: 0.05
  factor_data_root: ''
  fdr_method: benjamini_hochberg
  high_rank_threshold: 0.8
  ic_horizons:
  - 1
  - 3
  - 5
  - 10
  - 20
  legacy_format_priority: false
  log_level: INFO
  log_root: ''
  market_impact_coeff: 0.1
  max_cost_threshold: 0.01
  max_missing_ratio: 0.8
  max_vif_threshold: 10.0
  max_workers: 4
  memory_limit_gb: 8.0
  min_data_points: 50
  min_ic_threshold: 0.015
  min_ir_threshold: 0.35
  min_momentum_samples: 120
  min_robustness_score: 0.6
  min_sample_size: 100
  min_stability_threshold: 0.6
  name: default
  optimal_scoring_config_path: ./configs/optimal_fair_scoring_config.yaml
  output_dir: ''
  output_root: /Users/zhangshenshen/深度量化0927/factor_system/factor_screening/screening_results/0700.HK_20251012_051348
  price_data_root: ''
  progress_report_interval: 50
  raw_data_root: /Users/zhangshenshen/深度量化0927/factor_system/../raw
  rolling_window: 60
  sample_weight_params:
    affected_dimensions:
    - stability
    - independence
    - practicality
    enable: true
    min_full_weight_samples: 1000
    predictive_weight_power: 0.2
    thresholds:
      high_confidence: 2000
      low_confidence: 100
      medium_confidence: 500
    weight_power: 0.35
  save_detailed_metrics: true
  save_reports: true
  slippage_bps: 5.0
  symbols:
  - 0700.HK
  timeframe_adaptive_config:
    120min:
      alpha: 0.08
      tier1: 0.75
      tier2: 0.58
      tier3: 0.4
    15min:
      alpha: 0.07
      tier1: 0.8
      tier2: 0.65
      tier3: 0.45
    1day:
      alpha: 0.1
      tier1: 0.68
      tier2: 0.5
      tier3: 0.32
    1min:
      alpha: 0.05
      tier1: 0.85
      tier2: 0.7
      tier3: 0.5
    240min:
      alpha: 0.1
      tier1: 0.7
      tier2: 0.52
      tier3: 0.35
    2h:
      alpha: 0.1
      tier1: 0.72
      tier2: 0.55
      tier3: 0.38
    2min:
      alpha: 0.05
      tier1: 0.85
      tier2: 0.7
      tier3: 0.5
    30min:
      alpha: 0.07
      tier1: 0.78
      tier2: 0.62
      tier3: 0.42
    3min:
      alpha: 0.05
      tier1: 0.85
      tier2: 0.7
      tier3: 0.5
    4h:
      alpha: 0.1
      tier1: 0.7
      tier2: 0.52
      tier3: 0.35
    5min:
      alpha: 0.05
      tier1: 0.82
      tier2: 0.68
      tier3: 0.48
    60min:
      alpha: 0.08
      tier1: 0.75
      tier2: 0.58
      tier3: 0.4
  timeframe_alpha_map: {}
  timeframe_high_score_map:
    120min: 0.55
    15min: 0.58
    1day: 0.53
    1min: 0.6
    240min: 0.54
    2h: 0.55
    2min: 0.6
    30min: 0.57
    3min: 0.6
    4h: 0.54
    5min: 0.6
    60min: 0.56
  timeframe_tier_thresholds:
    120min:
      tier1: 0.72
      tier2: 0.55
      tier3: 0.38
      upgrade_tier1: 0.68
      upgrade_tier2: 0.48
    15min:
      tier1: 0.8
      tier2: 0.65
      tier3: 0.45
      upgrade_tier1: 0.75
      upgrade_tier2: 0.58
    1day:
      tier1: 0.68
      tier2: 0.5
      tier3: 0.32
      upgrade_tier1: 0.62
      upgrade_tier2: 0.42
    1min:
      tier1: 0.85
      tier2: 0.7
      tier3: 0.5
      upgrade_tier1: 0.8
      upgrade_tier2: 0.65
    240min:
      tier1: 0.7
      tier2: 0.52
      tier3: 0.35
      upgrade_tier1: 0.65
      upgrade_tier2: 0.45
    2h:
      tier1: 0.72
      tier2: 0.55
      tier3: 0.38
      upgrade_tier1: 0.68
      upgrade_tier2: 0.48
    2min:
      tier1: 0.85
      tier2: 0.7
      tier3: 0.5
      upgrade_tier1: 0.8
      upgrade_tier2: 0.65
    30min:
      tier1: 0.78
      tier2: 0.62
      tier3: 0.42
      upgrade_tier1: 0.72
      upgrade_tier2: 0.55
    3min:
      tier1: 0.85
      tier2: 0.7
      tier3: 0.5
      upgrade_tier1: 0.8
      upgrade_tier2: 0.65
    4h:
      tier1: 0.7
      tier2: 0.52
      tier3: 0.35
      upgrade_tier1: 0.65
      upgrade_tier2: 0.45
    5min:
      tier1: 0.82
      tier2: 0.68
      tier3: 0.48
      upgrade_tier1: 0.78
      upgrade_tier2: 0.62
    60min:
      tier1: 0.75
      tier2: 0.58
      tier3: 0.4
      upgrade_tier1: 0.7
      upgrade_tier2: 0.52
  timeframes:
  - 60min
  timeout_minutes: 60
  use_optimal_fair_scoring: true
  vif_threshold: 5.0
  weights:
    independence: 0.2
    practicality: 0.1
    predictive_power: 0.35
    short_term_fitness: 0.1
    stability: 0.25
