analysis:
  correlation_method: spearman
  correlation_min_periods: 30
  epsilon_small: 1.0e-08
  ic_periods:
  - 1
  - 5
  - 10
  - 20
  min_ic_observations: 20
  min_observations: 30
  min_ranking_samples: 5
  stability_split_ratio: 0.5
data_source:
  file_pattern: '*.parquet'
  panel_file: etf_rotation_system/data/factor_panel.parquet
  price_columns:
  - trade_date
  - close
  price_dir: raw/ETF/daily
  symbol_extract_method: stem_split
debug_mode: false
output:
  encoding: utf-8
  files:
    ic_analysis: ic_analysis.csv
    passed_factors: passed_factors.csv
    screening_report: screening_report.txt
  include_factor_details: true
  include_summary_statistics: true
  output_dir: etf_rotation_system/data/results/screening
  subdir_prefix: screening_
  timestamp_format: '%Y%m%d_%H%M%S'
  use_timestamp_subdir: true
progress_reporting: true
screening:
  fdr_alpha: 0.2
  max_correlation: 0.7
  max_pvalue: 0.2
  min_coverage: 0.7
  min_ic: 0.005
  min_ir: 0.05
  tier_labels:
    core: 🟢 核心
    research: 🔵 研究
    supplement: 🟡 补充
  tier_thresholds:
    core:
      ic: 0.02
      ir: 0.1
    research:
      ic: 0.0
      ir: 0.0
    supplement:
      ic: 0.01
      ir: 0.07
  use_fdr: true
