# 增强因子引擎配置

# 数据源配置
data_sources:
  # 价格数据源
  price:
    provider: "factor_system.factor_engine.providers.price_provider"
    data_dir: "raw/SH"
    cache_dir: "cache/price"

  # 资金流数据源
  money_flow:
    provider: "factor_system.factor_engine.providers.money_flow_provider_engine.MoneyFlowDataProvider"
    data_dir: "raw/SH/money_flow"
    price_dir: "raw/SH"  # 用于需要价格数据的资金流因子
    enforce_t_plus_1: true
    input_unit: "wan_yuan"
    output_unit: "yuan"

# 因子类别配置
factor_categories:
  # 技术因子
  technical:
    enabled: true
    data_source: "price"
    subcategories:
      - trend
      - momentum
      - volatility
      - volume
      - overlap

  # 资金流因子
  money_flow:
    enabled: true
    data_source: "money_flow"
    subcategories:
      - money_flow_core
      - money_flow_enhanced

# 因子集配置
factor_sets:
  # 混合因子集
  mixed_technical_money_flow:
    name: "技术+资金流混合因子集"
    description: "结合技术和资金流因子的综合因子集合"
    technical_factors:
      - RSI
      - MACD
      - SMA_20
      - ATR_14
    money_flow_factors:
      - MainNetInflow_Rate
      - OrderConcentration
      - MoneyFlow_Hierarchy
      - Flow_Price_Divergence
      - Institutional_Absorption

  # 资金流因子集
  money_flow_core:
    name: "资金流核心因子集"
    description: "基于主力资金流动的核心技术因子"
    factors:
      - MainNetInflow_Rate
      - LargeOrder_Ratio
      - SuperLargeOrder_Ratio
      - OrderConcentration
      - MoneyFlow_Hierarchy
      - MoneyFlow_Consensus
      - MainFlow_Momentum
      - Flow_Price_Divergence

  money_flow_enhanced:
    name: "资金流增强因子集"
    description: "结合资金流和价格行为的增强信号"
    factors:
      - Institutional_Absorption
      - Flow_Tier_Ratio_Delta
      - Flow_Reversal_Ratio

# 计算配置
computation:
  # 缓存配置
  cache:
    enabled: true
    memory_mb: 2048
    disk_mb: 8192
    ttl_hours: 24

  # 并行计算配置
  parallel:
    enabled: true
    n_jobs: 4
    max_memory_per_job_mb: 512

  # 内存管理
  memory:
    max_total_mb: 4096
    gc_threshold_mb: 1024

# 输出配置
output:
  # 文件格式
  format: "parquet"

  # 压缩
  compression: "snappy"

  # 元数据
  include_metadata: true
  include_timestamps: true

# 验证配置
validation:
  # 时序安全验证
  temporal_safety:
    enabled: true
    strict_mode: true

  # 数据质量验证
  data_quality:
    min_coverage_ratio: 0.8
    max_missing_ratio: 0.1
    outlier_detection: true

  # 因子有效性验证
  factor_validity:
    min_ic_threshold: 0.03
    max_correlation_threshold: 0.7