# 技术指标因子生产配置（150+指标全量计算）
# Linus准则：向量化、批处理、可追溯

# ============================================================
# 数据路径配置
# ============================================================
data_paths:
  # 价格数据目录
  price_data_dir: "raw/HK"
  
  # 输出目录
  output_root: "factor_system/factor_output"
  technical_output: "factor_system/factor_output/technical"
  
  # 日志目录
  log_dir: "logs/technical_factors"

# ============================================================
# 时间范围配置
# ============================================================
time_config:
  # 数据时间范围
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  
  # 时间框架（支持多时间框架）
  timeframes:
    - "15min"
    - "30min"
    - "60min"
    - "120min"
    - "1day"

# ============================================================
# 标的配置
# ============================================================
symbols:
  mode: "auto_scan"  # auto_scan | manual
  
  # 手动指定标的
  manual_list:
    - "0700.HK"
    - "0005.HK"
  
  # 市场过滤
  markets:
    - "HK"

# ============================================================
# 因子配置（150+技术指标）
# ============================================================
factors:
  # 计算模式
  mode: "all"  # all | category | custom
  
  # 按类别计算（mode=category时使用）
  categories:
    - "trend"        # 趋势指标
    - "momentum"     # 动量指标
    - "volatility"   # 波动率指标
    - "volume"       # 成交量指标
    - "overlap"      # 重叠指标
    - "pattern"      # K线形态
    - "statistic"    # 统计因子
  
  # 自定义因子列表（mode=custom时使用）
  custom_factors: []
  
  # 因子参数优化
  optimize_parameters: false

# ============================================================
# 执行配置
# ============================================================
execution:
  # 并行处理
  parallel: true
  n_jobs: -1  # -1表示使用所有CPU核心
  
  # 批处理
  batch_size: 5
  
  # 缓存
  use_cache: true
  cache_dir: ".cache/technical_factors"
  
  # 内存管理
  max_memory_gb: 8
  chunk_size: 1000  # 每次处理的K线数量

# ============================================================
# 输出配置
# ============================================================
output:
  format: "parquet"
  compression: "snappy"
  
  # 分文件保存策略
  split_by: "symbol"  # symbol | timeframe | none
  
  # 文件命名
  filename_template: "{symbol}_{timeframe}_factors_{start_date}_{end_date}.parquet"
  
  # 报告
  generate_report: true
  report_format: "markdown"

# ============================================================
# 质量控制
# ============================================================
quality_control:
  validate_data: true
  handle_missing: "forward_fill"
  detect_outliers: true
  outlier_threshold: 5.0

# ============================================================
# 日志配置
# ============================================================
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file_logging: true
  console_logging: true
