# ETF轮动精细策略配置文件
# 独立于VBT的完整策略分析和优化配置

# === 项目基本信息 ===
project:
  name: "ETF轮动精细策略系统"
  version: "1.0.0"
  description: "基于VBT回测结果的精细化策略分析和优化系统"
  author: "Claude Code Assistant"

# === 数据路径配置 ===
data_paths:
  # VBT回测结果路径
  vbt_results_base: "/Users/zhangshenshen/深度量化0927/etf_rotation_system/data/results/backtest"

  # 精细策略数据路径
  analysis_output: "/Users/zhangshenshen/深度量化0927/etf_rotation_system/04_精细策略/output"
  cache_dir: "/Users/zhangshenshen/深度量化0927/etf_rotation_system/04_精细策略/cache"
  log_dir: "/Users/zhangshenshen/深度量化0927/etf_rotation_system/04_精细策略/logs"

# === 分析配置 ===
analysis_config:
  # 分析参数
  top_strategies_count: 50          # 分析前50个最优策略
  min_usage_rate: 0.3               # 最小因子使用率
  min_sharpe_threshold: 0.45        # 最小夏普比率阈值

  # 相关性分析
  correlation_threshold: 0.7         # 高相关性阈值

  # 统计分析
  percentiles: [1, 5, 10, 25, 50, 75, 90, 95, 99]
  confidence_level: 0.95

# === 筛选配置 ===
screening_config:
  # 基本筛选标准
  min_sharpe_ratio: 0.45            # 最小夏普比率
  max_drawdown_threshold: -45.0     # 最大回撤阈值
  min_total_return: 40.0            # 最小总收益

  # 权重约束
  max_single_weight: 0.6            # 单个因子最大权重
  min_effective_factors: 2          # 最小有效因子数
  max_effective_factors: 5          # 最大有效因子数

  # 候选生成
  candidate_generation:
    total_candidates: 3000           # 总候选数量
    random_sampling_ratio: 0.5       # 随机采样比例
    systematic_ratio: 0.5            # 系统性组合比例
    weight_noise_scale: 0.1          # 权重噪声尺度

  # 性能参数
  n_workers: 8                      # 并行工作进程数
  chunk_size: 100                   # 批处理大小
  enable_cache: true                # 启用缓存

# === 优化配置 ===
optimization_config:
  # 遗传算法参数
  genetic_algorithm:
    max_iterations: 500              # 最大迭代次数
    population_size: 30              # 种群大小
    mutation_rate: 0.1               # 变异率
    crossover_rate: 0.8              # 交叉率
    tournament_size: 3               # 锦标赛大小

  # 局部搜索
  local_search:
    enable: true                     # 启用局部搜索
    radius: 0.05                     # 搜索半径
    attempts: 10                     # 搜索尝试次数

  # 收敛控制
  convergence:
    threshold: 1e-6                  # 收敛阈值
    patience: 10                     # 耐心值（代数）
    min_improvement: 1e-5            # 最小改进幅度

  # 目标函数权重
  objective_weights:
    sharpe_ratio: 0.7                # 夏普比率权重
    total_return: 0.2                # 总收益权重
    max_drawdown: 0.1                # 回撤权重

  # 约束条件
  constraints:
    weight_sum_tolerance: 0.01       # 权重和容差
    min_weight: 0.001                # 最小权重
    max_weight: 0.7                  # 最大权重
    min_factors: 2                   # 最少因子数
    max_factors: 5                   # 最多因子数

  # 性能参数
  n_workers: 6                      # 并行工作进程数
  chunk_size: 20                    # 批处理大小

# === 策略模板配置 ===
strategy_templates:
  # 核心因子策略
  core_strategy:
    name: "核心因子策略"
    description: "聚焦最高效的4个因子，追求最高夏普比率"
    risk_level: "medium"
    expected_sharpe: 0.47
    max_factors: 4

  # 平衡策略
  balanced_strategy:
    name: "平衡策略"
    description: "结合核心和补充因子，平衡风险和收益"
    risk_level: "medium_low"
    expected_sharpe: 0.45
    max_factors: 5

  # 保守策略
  conservative_strategy:
    name: "保守策略"
    description: "使用最稳定的2个因子，控制回撤风险"
    risk_level: "low"
    expected_sharpe: 0.44
    max_factors: 2

# === 因子配置 ===
factors:
  # 核心因子定义
  core_factors:
    - name: "RSI_6"
      category: "momentum"
      description: "6日相对强弱指标"
      importance: 1.0
      typical_weight_range: [0.35, 0.50]

    - name: "VOL_VOLATILITY_20"
      category: "volume"
      description: "20日成交量波动率"
      importance: 0.9
      typical_weight_range: [0.20, 0.30]

    - name: "VOLATILITY_120D"
      category: "volatility"
      description: "120日价格波动率"
      importance: 0.8
      typical_weight_range: [0.10, 0.20]

    - name: "INTRADAY_POSITION"
      category: "position"
      description: "日内位置指标"
      importance: 0.7
      typical_weight_range: [0.15, 0.25]

  # 补充因子定义
  supplementary_factors:
    - name: "VOLUME_PRICE_TREND"
      category: "trend"
      description: "量价趋势指标"
      importance: 0.6
      typical_weight_range: [0.05, 0.15]

    - name: "INTRA_DAY_RANGE"
      category: "range"
      description: "日内波动范围"
      importance: 0.5
      typical_weight_range: [0.05, 0.15]

# === 输出配置 ===
output_config:
  # 文件命名
  file_naming:
    analysis_results: "analysis_results.json"
    screening_results: "screening_results.json"
    optimization_results: "optimization_results.json"
    final_report: "final_strategy_report.json"

  # 报告配置
  reporting:
    include_charts: false             # 是否包含图表
    include_detailed_stats: true      # 是否包含详细统计
    include_factor_analysis: true     # 是否包含因子分析
    include_optimization_history: true # 是否包含优化历史

  # 格式配置
  format:
    json_indent: 2                   # JSON缩进
    decimal_places: 4                # 小数位数
    percentage_format: ".2%"         # 百分比格式

# === 日志配置 ===
logging_config:
  level: "INFO"                      # 日志级别
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  # 文件日志
  file_logging:
    enabled: true
    max_file_size: "10MB"
    backup_count: 5
    rotation: "daily"

  # 控制台日志
  console_logging:
    enabled: true
    colored: true

# === 缓存配置 ===
cache_config:
  enabled: true                      # 启用缓存
  ttl_seconds: 3600                  # 缓存生存时间（1小时）
  max_size_mb: 100                   # 最大缓存大小
  cleanup_interval: 1800             # 清理间隔（30分钟）

# === 验证配置 ===
validation_config:
  # 策略验证
  strategy_validation:
    enable_out_of_sample_test: true   # 启用样本外测试
    out_of_sample_ratio: 0.2         # 样本外比例
    min_validation_periods: 50       # 最小验证周期

  # 风险验证
  risk_validation:
    max_volatility: 0.25             # 最大波动率
    var_confidence: 0.95              # VaR置信度
    stress_test_scenarios: 5          # 压力测试场景数

# === 高级配置 ===
advanced_config:
  # 贝叶斯优化（可选）
  bayesian_optimization:
    enabled: false                    # 默认禁用
    n_iterations: 100
    acquisition_function: "ei"
    exploration_factor: 0.1

  # 多目标优化（可选）
  multi_objective:
    enabled: false                    # 默认禁用
    objectives: ["sharpe_ratio", "total_return", "max_drawdown"]
    pareto_front_size: 10

  # 机器学习增强（可选）
  ml_enhancement:
    enabled: false                    # 默认禁用
    model_type: "random_forest"
    feature_engineering: true
    cross_validation_folds: 5

# === 调试配置 ===
debug_config:
  verbose_logging: false             # 详细日志
  save_intermediate_results: false   # 保存中间结果
  profiling_enabled: false           # 性能分析
  memory_tracking: false             # 内存跟踪

# === 运行配置 ===
execution_config:
  # 运行模式
  run_mode: "development"            # development | production

  # 资源限制
  resource_limits:
    max_memory_gb: 8.0               # 最大内存使用
    max_cpu_cores: 8                 # 最大CPU核心数
    timeout_seconds: 3600            # 超时时间

  # 并行配置
  parallel:
    enable_parallel: true            # 启用并行处理
    max_workers: 8                   # 最大工作进程数
    chunk_size: 50                   # 批处理大小