# A股因子计算配置
# 针对A股市场特征优化的参数设置

market: "A_SHARES"
enable_all_periods: true
enable_manual_indicators: true

# A股交易时间
trading_hours:
  morning_start: "09:30"
  morning_end: "11:30"
  afternoon_start: "13:00"
  afternoon_end: "15:00"

# A股成本模型
transaction_costs:
  commission_rate: 0.0003  # 佣金 0.03%
  stamp_duty: 0.001        # 印花税 0.1% (卖出)
  transfer_fee: 0.00002    # 过户费 0.002%
  slippage_bps: 5          # 滑点 5 bps

# 时间框架参数（针对A股优化）
timeframe_params:
  "1min":
    ma_windows: [3, 5, 10, 15, 20]
    ema_spans: [3, 5, 10, 15, 20]
    rsi_windows: [7, 14, 21]
    bb_windows: [10, 20]
    atr_windows: [10, 14]
    
  "5min":
    ma_windows: [3, 5, 8, 10, 15, 20]
    ema_spans: [3, 5, 8, 12, 15, 20]
    rsi_windows: [7, 10, 14]
    bb_windows: [10, 15, 20]
    atr_windows: [7, 10, 14]
    
  "15min":
    ma_windows: [5, 8, 10, 15, 20, 30]
    ema_spans: [5, 8, 12, 15, 20, 26]
    rsi_windows: [10, 14, 20]
    bb_windows: [15, 20, 25]
    atr_windows: [10, 14, 20]
    
  "30min":
    ma_windows: [8, 10, 15, 20, 30, 40]
    ema_spans: [8, 12, 15, 20, 26, 30]
    rsi_windows: [14, 20, 25]
    bb_windows: [20, 25, 30]
    atr_windows: [14, 20, 25]
    
  "60min":
    ma_windows: [10, 15, 20, 30, 40, 50]
    ema_spans: [12, 15, 20, 26, 30, 40]
    rsi_windows: [14, 20, 30]
    bb_windows: [20, 30, 40]
    atr_windows: [14, 20, 30]
    
  "1day":
    ma_windows: [5, 10, 20, 30, 60, 120, 250]
    ema_spans: [12, 20, 26, 30, 60, 120]
    rsi_windows: [6, 12, 24]
    bb_windows: [20, 30, 60]
    atr_windows: [14, 20, 60]

# A股特色因子参数
a_share_specific:
  # 涨跌停板
  limit_up_threshold: 0.10    # 10%涨停
  limit_down_threshold: -0.10 # 10%跌停
  st_limit_threshold: 0.05    # ST股5%涨跌停
  
  # 换手率异常阈值
  turnover_high_threshold: 0.15  # 15%换手率为高
  turnover_low_threshold: 0.01   # 1%换手率为低
  
  # 尾盘效应窗口
  tail_window_minutes: 30  # 最后30分钟
  
  # 资金流因子
  enable_northbound_flow: false  # 北向资金（需额外数据源）
  enable_margin_trading: false   # 融资融券（需额外数据源）

# 后处理配置
postprocess:
  drop_empty_columns: true      # 删除全空/全常数列
  min_valid_ratio: 0.05         # 最小有效值比例（低于此比例的列将被删除）
  log_coverage: true            # 记录因子覆盖率统计

# 性能优化配置
performance:
  use_batch_ops: true           # 使用批量计算（5-10x加速）
  enable_cache: true            # 启用VectorBT缓存
  cache_mode: full              # 缓存模式: full/partial/off
  n_jobs: -1                    # 并行任务数（-1=所有CPU核心）
  chunked: auto                 # 分块处理: auto/true/false

# TA-Lib扩展指标
ta_indicators:
  # Hilbert Transform系列
  hilbert_transform:
    - HT_DCPERIOD    # 主导周期
    - HT_DCPHASE     # 主导相位
    - HT_TRENDMODE   # 趋势模式
    - HT_PHASOR      # 相量
    - HT_SINE        # 正弦波
  
  # MAMA系列
  mama:
    - MAMA           # MESA自适应移动平均
  
  # 其他高级指标
  advanced:
    - KAMA           # Kaufman自适应移动平均
