# 生产因子快照
# 版本ID: 20251015_150021
# 生成时间: 2025-10-15T15:00:21.957875
# 引擎版本: 1.0.0
# 价格字段: None

production_factors:
  - TA_RSI_14
  - VBT_MACD_SIGNAL_12_26_9
  - VBT_MA_5
  - VBT_ATR_7
  - TA_ATR_14
  - VOLATILITY_20
  - VOLUME_RATIO_10
  - RETURN_5
  - RETURN_20
  - MOMENTUM_10
  - PRICE_POSITION_20
  - VBT_OBV
