# ETF Rotation System - Backtest Configuration
# Generated: 2025-10-22

backtest:
  # 成本模型 (港股)
  commission_rate: 0.002       # 佣金 0.2%
  stamp_duty: 0.001            # 印花税 0.1%
  slippage_hkd: 0.05           # 滑点 0.05 HKD
  
  # 组合参数
  n_jobs: -1                   # 并行核心数 (-1表示全部)
  init_cash: 1000000           # 初始资金 100万
  
  # 轮动参数
  top_n: 5                     # 选股数量
  rebalance_freq: "1W"         # 调仓频率
  
  # 权重方案
  weight_schemes:
    - "equal"                  # 等权
    - "rank"                   # 排名加权
    - "score"                  # 分数加权
  
  # 惩罚系数
  turnover_penalties: [0.0, 0.001, 0.002, 0.003, 0.005]
