# Linus混合策略配置
# 战略层(月度) + 战术层(周度) 双频率轮动
# 基于数据验证: 长周期因子IC_5D更高,但低换手;短周期因子灵敏

# ========== 战略层配置 (Strategic Layer) ==========
strategic:
  # 调仓频率
  rebalance_freq: "1M"  # 月度调仓 (20个交易日)
  
  # 选股数量
  top_n: 3  # 精选3只
  
  # 战略因子 (长周期,IC高)
  factors:
    - PRICE_POSITION_60D      # IC_5D=+0.0463, IR_5D=+0.138
    - DISTANCE_TO_52W_HIGH    # IC_5D=+0.0388, IR_5D=+0.109
    - MOMENTUM_252D           # IC_5D=+0.0427, IR_5D=+0.118 (未通过但IC高)
    - VOLATILITY_120D         # IC_5D=-0.0290 (风险控制)
    - DRAWDOWN_RECOVERY_SPEED # IC_5D=+0.0262 (质量因子)
  
  # 因子权重
  factor_weights:
    PRICE_POSITION_60D: 0.30
    DISTANCE_TO_52W_HIGH: 0.25
    MOMENTUM_252D: 0.20
    VOLATILITY_120D: 0.15  # 负向因子,低波动优先
    DRAWDOWN_RECOVERY_SPEED: 0.10
  
  # 组合权重
  portfolio_weight: 0.70  # 战略层占总资金70%
  
  # 权重方案
  weight_scheme: "score"  # 分数加权

# ========== 战术层配置 (Tactical Layer) ==========
tactical:
  # 调仓频率
  rebalance_freq: "1W"  # 周度调仓 (5个交易日)
  
  # 选股数量
  top_n: 5  # 分散5只
  
  # 战术因子 (短周期,灵敏)
  factors:
    - MOM_ACCEL                # IC_5D=-0.0499, IR_5D=-0.141
    - WR_14                    # IC_5D=+0.0368, IR_5D=+0.119
    - VOLATILITY_REGIME_SHIFT  # IC_5D=+0.0271, IR_5D=+0.100
    - RSI_14                   # IC_5D=+0.0252, IR_5D=+0.078
    - VOL_VOLATILITY_20        # IC_5D=+0.0169, IR_5D=+0.083
  
  # 因子权重
  factor_weights:
    MOM_ACCEL: 0.30
    WR_14: 0.25
    VOLATILITY_REGIME_SHIFT: 0.20
    RSI_14: 0.15
    VOL_VOLATILITY_20: 0.10
  
  # 组合权重
  portfolio_weight: 0.30  # 战术层占总资金30%
  
  # 权重方案
  weight_scheme: "rank"  # 排名加权

# ========== 成本模型 (港股标准) ==========
costs:
  commission_rate: 0.002   # 佣金 0.2%
  stamp_duty: 0.001        # 印花税 0.1%
  slippage_hkd: 0.05       # 滑点 0.05 HKD

# ========== 风控参数 ==========
risk_control:
  # 止损止盈 (战术层)
  stop_loss: -0.08         # 8%止损
  take_profit: 0.15        # 15%止盈
  trailing_stop: 0.10      # 10%移动止损
  
  # 仓位限制
  max_position_size: 0.20  # 单只最大20%
  min_position_size: 0.05  # 单只最小5%
  
  # 集中度控制
  max_sector_exposure: 0.40  # 单行业最大40%

# ========== 回测参数 ==========
backtest:
  init_cash: 1000000       # 初始资金 100万
  start_date: "2020-01-01"
  end_date: "2024-12-31"
  
  # 组合再平衡
  rebalance_mode: "independent"  # 战略/战术独立调仓
  
  # 性能指标
  benchmark: "000300.SH"   # 沪深300
  risk_free_rate: 0.02     # 无风险利率 2%

# ========== 输出配置 ==========
output:
  save_dir: "data/results/hybrid_strategy"
  save_signals: true       # 保存信号
  save_positions: true     # 保存持仓
  save_trades: true        # 保存交易
  save_metrics: true       # 保存指标

# ========== 日志配置 ==========
logging:
  level: "INFO"
  format: "%(asctime)s [%(levelname)s] %(message)s"
  save_log: true
