# 优化筛选配置 - 基于现有35个优质因子
# 目标：从35个因子中精选15-20个，解决过拟合问题

analysis:
  correlation_method: spearman
  correlation_min_periods: 30
  epsilon_small: 1.0e-08
  ic_periods:
  - 1
  - 5
  - 10
  - 20
  min_ic_observations: 20
  min_observations: 30
  min_ranking_samples: 5
  stability_split_ratio: 0.5

data_source:
  file_pattern: '*.parquet'
  panel_file: /Users/zhangshenshen/深度量化0927/etf_rotation_system/data/results/panels/panel_20251024_214306/panel.parquet
  price_columns:
  - trade_date
  - close
  price_dir: raw/ETF/daily
  symbol_extract_method: stem_split

debug_mode: false

output:
  encoding: utf-8
  files:
    ic_analysis: optimized_ic_analysis.csv
    passed_factors: optimized_passed_factors.csv
    screening_report: optimized_screening_report.txt
  include_factor_details: true
  include_summary_statistics: true
  output_dir: etf_rotation_system/data/results/optimized_screening
  subdir_prefix: optimized_screening_
  timestamp_format: '%Y%m%d_%H%M%S'
  use_timestamp_subdir: true

progress_reporting: true

screening:
  fdr_alpha: 0.2  # 进一步放宽FDR控制
  force_include_factors:
    - "RSI_14"  # 强制包含核心技术指标
    - "WR_14"   # 强制包含威廉指标
    - "TREND_CONSISTENCY"  # 强制包含趋势一致性
    - "CS_RANK_PERCENTILE"  # 强制包含横截面排名
    - "ROTATION_SCORE"  # 强制包含轮动分数
  ic_period_for_screening: ic_5d
  max_correlation: 0.75  # 适度控制相关性
  max_factors: 18  # 目标18个因子
  max_pvalue: 0.15  # 进一步放宽p值
  min_coverage: 0.65  # 进一步降低覆盖率要求
  min_ic: 0.003  # 大幅降低IC阈值到0.3%
  min_ir: 0.03  # 大幅降低IR阈值
  priority_metric: ic_ir
  target_rebalance_period: 5
  tier_labels:
    core: 🟢 核心
    research: 🔵 研究
    supplement: 🟡 补充
  tier_thresholds:
    core:
      ic: 0.008  # 降低核心因子要求
      ir: 0.06
    research:
      ic: 0.004
      ir: 0.04
    supplement:
      ic: 0.002
      ir: 0.02
  use_fdr: true
  use_period_specific_ic: true

# 优化因子权重配置
factor_weights:
  # 动量类因子（选择4-5个代表性因子）
  momentum:
    MOMENTUM_63D: 0.07
    MOM_ACCEL: 0.06
    RELATIVE_STRENGTH_20D: 0.07
    TREND_CONSISTENCY: 0.06

  # 技术指标类因子
  technical:
    RSI_14: 0.08
    WR_14: 0.07
    # 可考虑后续添加MACD

  # 波动率类因子（选择2-3个）
  volatility:
    VOLATILITY_120D: 0.07
    ATR_14: 0.06
    VOLATILITY_REGIME_SHIFT: 0.05

  # 价格位置类因子（选择2-3个）
  price_position:
    PRICE_POSITION_60D: 0.07
    DISTANCE_TO_52W_HIGH: 0.06
    INTRADAY_POSITION: 0.05

  # 量价关系类因子（选择2个）
  volume_price:
    VOLUME_RATIO_20D: 0.06
    VOLUME_PRICE_TREND: 0.06

  # 横截面因子（保留所有，这是您的优势）
  cross_section:
    CS_RANK_PERCENTILE: 0.08
    CS_RANK_CHANGE_5D: 0.07
    ROTATION_SCORE: 0.07
    VOL_ADJUSTED_EXCESS: 0.06
    RS_DEVIATION: 0.06

  # 风险因子（选择1-2个）
  risk:
    DRAWDOWN_126D: 0.05
    EXTREME_RETURN_FREQ: 0.04

# 因子去重配置
factor_deduplication:
  enabled: true
  correlation_threshold: 0.8
  priority_factors:
    - "RSI_14"  # 优先保留RSI
    - "CS_RANK_PERCENTILE"  # 优先保留横截面排名
    - "ROTATION_SCORE"  # 优先保留轮动分数
    - "MOMENTUM_63D"  # 优先保留中期动量
    - "VOLATILITY_120D"  # 优先保留长期波动率

  # 冗余因子组（每组只保留最优的1个）
  redundant_groups:
    relative_momentum_group:
      - "RELATIVE_MOMENTUM_20D"
      - "RELATIVE_MOMENTUM_60D"
      - "RELATIVE_MOMENTUM_20D_ZSCORE"
      - "RELATIVE_MOMENTUM_60D_ZSCORE"
      keep: "RELATIVE_MOMENTUM_20D"  # 保留20日相对动量

    zscore_group:
      - "CS_RANK_CHANGE_5D_ZSCORE"
      - "VOL_ADJUSTED_EXCESS_ZSCORE"
      - "RS_DEVIATION_ZSCORE"
      keep: "CS_RANK_CHANGE_5D_ZSCORE"  # 保留横截面排名变化