"""
因子列表模块 - 提供分类的因子列表以避免大文件结构问题
"""

from .core_factors import (
    CORE_FACTORS,
    CORE_MONEY_FLOW_FACTORS,
    ENHANCED_MONEY_FLOW_FACTORS,
    ALL_CORE_FACTORS,
)

from .generated_technical_factors import GENERATED_TECHNICAL_FACTORS
from .generated_candlestick_factors import GENERATED_CANDLESTICK_FACTORS
from .generated_statistical_factors import GENERATED_STATISTICAL_FACTORS
from .generated_volume_factors import GENERATED_VOLUME_FACTORS
from .generated_overlap_factors import GENERATED_OVERLAP_FACTORS

# 完整的生成因子列表
ALL_GENERATED_FACTORS = (
    GENERATED_TECHNICAL_FACTORS +
    GENERATED_CANDLESTICK_FACTORS +
    GENERATED_STATISTICAL_FACTORS +
    GENERATED_VOLUME_FACTORS +
    GENERATED_OVERLAP_FACTORS
)

# 所有因子列表
ALL_FACTORS = ALL_CORE_FACTORS + ALL_GENERATED_FACTORS

__all__ = [
    'CORE_FACTORS',
    'CORE_MONEY_FLOW_FACTORS',
    'ENHANCED_MONEY_FLOW_FACTORS',
    'ALL_CORE_FACTORS',
    'GENERATED_TECHNICAL_FACTORS',
    'GENERATED_CANDLESTICK_FACTORS',
    'GENERATED_STATISTICAL_FACTORS',
    'GENERATED_VOLUME_FACTORS',
    'GENERATED_OVERLAP_FACTORS',
    'ALL_GENERATED_FACTORS',
    'ALL_FACTORS',
]