name: Factor Panel CI

on:
  push:
    paths:
      - 'factor_system/**'
      - 'scripts/produce_full_etf_panel.py'
      - 'factor_output/**/*.parquet'
  pull_request:
    paths:
      - 'factor_system/**'
      - 'scripts/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install pandas numpy pyyaml
      
      - name: Run CI Checks
        run: |
          python3 scripts/ci_checks.py
        continue-on-error: false
      
      - name: Block if Failed
        if: failure()
        run: |
          echo "❌ CI检查失败，阻断面板放行"
          exit 1
      
      - name: Generate Report
        if: always()
        run: |
          echo "## CI检查报告" >> $GITHUB_STEP_SUMMARY
          echo "- 静态扫描: shift(1)强制检查" >> $GITHUB_STEP_SUMMARY
          echo "- 索引规范: MultiIndex(symbol, date)" >> $GITHUB_STEP_SUMMARY
          echo "- 覆盖率: ≥80%" >> $GITHUB_STEP_SUMMARY
          echo "- 有效因子数: ≥8" >> $GITHUB_STEP_SUMMARY
          echo "- 零方差: =0" >> $GITHUB_STEP_SUMMARY
